import type { ExpenseCategory } from "./types";

/**
 * Semantic prototypes.
 *
 * A category is compared against several short sentences that mean it, in
 * every language the instance cares about, rather than against its name. The
 * name alone is a poor anchor: "Autre" and "Other" sit near everything, and a
 * multilingual model puts `dîner` next to `dinner` only if it has both to
 * compare against.
 *
 * Keep them short, concrete and phrased like a purchase. Adding a language
 * means appending its phrases to each list — nothing else changes.
 *
 * `other` has none. Nothing is semantically similar to "not classified".
 */
export const CATEGORY_PROTOTYPES: Readonly<
  Partial<Record<ExpenseCategory, readonly string[]>>
> = {
  groceries: [
    "groceries",
    "grocery store",
    "supermarket",
    "food shopping",
    "courses alimentaires",
    "supermarché",
    "épicerie",
    "achat alimentaire",
  ],
  restaurants: [
    "restaurant",
    "coffee shop",
    "food delivery",
    "dinner with friends",
    "lunch",
    "drinks at the bar",
    "ice cream on the way home",
    "café",
    "livraison de repas",
    "dîner au restaurant",
    "déjeuner",
    "un verre au bar",
    "une glace en rentrant",
  ],
  transport: [
    "train ticket",
    "bus fare",
    "taxi ride",
    "parking",
    "fuel for the car",
    "billet de train",
    "transports publics",
    "essence",
    "place de parking",
  ],
  housing: [
    "monthly rent",
    "mortgage payment",
    "landlord",
    "service charges for the flat",
    "loyer mensuel",
    "charges de copropriété",
    "régie immobilière",
  ],
  utilities: [
    "electricity bill",
    "water bill",
    "internet subscription at home",
    "mobile phone bill",
    "heating",
    "facture d'électricité",
    "facture d'eau",
    "abonnement internet",
    "chauffage",
  ],
  shopping: [
    "clothes",
    "electronics",
    "furniture for the flat",
    "online order",
    "shoes",
    "vêtements",
    "électroménager",
    "meubles",
    "achat en ligne",
  ],
  health: [
    "doctor's appointment",
    "pharmacy",
    "dentist",
    "prescription medicine",
    "glasses",
    "rendez-vous chez le médecin",
    "pharmacie",
    "dentiste",
    "médicaments",
  ],
  entertainment: [
    "cinema ticket",
    "concert",
    "theatre show",
    "video game",
    "night out",
    "place de cinéma",
    "concert",
    "spectacle",
    "jeu vidéo",
  ],
  travel: [
    "flight ticket",
    "plane tickets for the holiday",
    "travel agency booking",
    "airport transfer",
    "billet d'avion",
    "réservation de voyage",
    "agence de voyage",
    "navette pour l'aéroport",
  ],
  lodging: [
    "hotel night",
    "holiday accommodation",
    "the airbnb for the weekend",
    "campsite pitch",
    "mountain hut for the night",
    "nuit d'hôtel",
    "location de vacances",
    "le gîte pour le week-end",
    "emplacement de camping",
    "cabane pour la nuit",
  ],
  activities: [
    "museum entry",
    "guided tour of the old town",
    "ski pass for the day",
    "escape room with friends",
    "entry to the theme park",
    "entrée au musée",
    "visite guidée",
    "forfait de ski",
    "escape game entre amis",
    "entrée au parc d'attractions",
  ],
  household: [
    "cleaning products for the flat",
    "a new sofa",
    "light bulbs and batteries",
    "the plumber came round",
    "toilet paper and washing powder",
    "produits d'entretien",
    "un nouveau canapé",
    "ampoules et piles",
    "passage du plombier",
    "papier toilette et lessive",
  ],
  subscriptions: [
    "monthly subscription",
    "streaming service",
    "annual membership",
    "cloud storage plan",
    "abonnement mensuel",
    "service de streaming",
    "adhésion annuelle",
  ],
  family: [
    "childcare",
    "nursery fees",
    "babysitter",
    "school supplies",
    "kids activity",
    "garde d'enfants",
    "crèche",
    "cantine scolaire",
    "fournitures scolaires",
  ],
  pets: [
    "pet food",
    "veterinarian",
    "dog grooming",
    "cat litter",
    "nourriture pour chien",
    "vétérinaire",
    "toilettage",
    "animalerie",
  ],
  gifts: [
    "birthday present",
    "wedding gift",
    "charity donation",
    "flowers for someone",
    "cadeau d'anniversaire",
    "cadeau de mariage",
    "don à une association",
    "livraison de fleurs",
  ],
  fees: [
    "bank charges",
    "card fee",
    "currency conversion fee",
    "late payment fee",
    "frais bancaires",
    "frais de carte",
    "frais de change",
    "frais de retard",
  ],
};
