import type { ExpenseCategory } from "./types";

/**
 * Semantic prototypes.
 *
 * A category is compared against several short sentences that mean it, in
 * every language the instance cares about, rather than against its name. The
 * name alone is a poor anchor: "Autre" and "Other" sit near everything, and a
 * multilingual model puts `dîner` next to `dinner` only if it has both to
 * compare against.
 *
 * Keep them short, concrete and phrased like a purchase. Adding a language
 * means appending its phrases to each list — nothing else changes.
 *
 * `other` has none. Nothing is semantically similar to "not classified".
 */
export const CATEGORY_PROTOTYPES: Readonly<
  Partial<Record<ExpenseCategory, readonly string[]>>
> = {
  groceries: [
    "groceries",
    "grocery store",
    "supermarket",
    "food shopping",
    "courses alimentaires",
    "supermarché",
    "épicerie",
    "achat alimentaire",
  ],
  restaurants: [
    "restaurant",
    "coffee shop",
    "food delivery",
    "dinner with friends",
    "lunch",
    "drinks at the bar",
    "ice cream on the way home",
    "café",
    "livraison de repas",
    "dîner au restaurant",
    "déjeuner",
    "un verre au bar",
    "une glace en rentrant",
  ],
  transport: [
    "buying a car",
    "the monthly leasing payment",
    "the garage fixed the car",
    "the car registration",
    "train ticket",
    "bus fare",
    "taxi ride",
    "parking",
    "fuel for the car",
    "flight ticket",
    "airport transfer",
    "billet de train",
    "transports publics",
    "essence",
    "place de parking",
    "billet d'avion",
    "navette pour l'aéroport",
    "achat d'une voiture",
    "la mensualité du leasing",
    "réparation au garage",
    "la carte grise",
  ],
  /**
   * One place, three former codes: the rent, the bills and the upkeep. The
   * anchors of all three are kept, because a category is compared against
   * several sentences that mean it and `home` genuinely means all of these.
   */
  home: [
    "monthly rent",
    "mortgage payment",
    "landlord",
    "service charges for the flat",
    "electricity bill",
    "water bill",
    "internet subscription at home",
    "mobile phone bill",
    "heating",
    "cleaning products for the flat",
    "a new sofa",
    "light bulbs and batteries",
    "the plumber came round",
    "toilet paper and washing powder",
    "the deposit on the house",
    "the removal van",
    "a self-storage unit",
    "the rental deposit",
    "loyer mensuel",
    "charges de copropriété",
    "régie immobilière",
    "facture d'électricité",
    "facture d'eau",
    "abonnement internet",
    "chauffage",
    "produits d'entretien",
    "un nouveau canapé",
    "ampoules et piles",
    "passage du plombier",
    "papier toilette et lessive",
    "l'apport pour la maison",
    "le camion de déménagement",
    "un box de stockage",
    "le dépôt de garantie",
  ],
  shopping: [
    "clothes",
    "electronics",
    "a pair of shoes",
    "online order",
    "a book",
    "sports equipment",
    "toys for the children",
    "vêtements",
    "une paire de chaussures",
    "achat en ligne",
    "un livre",
    "matériel de sport",
    "des jouets",
  ],
  personal_care: [
    "haircut",
    "the hairdresser",
    "a manicure",
    "shampoo and toothpaste",
    "an afternoon at the spa",
    "dry cleaning",
    "coiffeur",
    "une coupe de cheveux",
    "manucure",
    "shampoing et dentifrice",
    "un après-midi au spa",
    "pressing",
  ],
  education: [
    "university tuition",
    "the school fees",
    "a language course",
    "professional training",
    "textbooks for the course",
    "frais de scolarité",
    "les frais d'école",
    "un cours de langue",
    "une formation professionnelle",
    "manuels de cours",
  ],
  health: [
    "doctor's appointment",
    "pharmacy",
    "dentist",
    "prescription medicine",
    "glasses",
    "rendez-vous chez le médecin",
    "pharmacie",
    "dentiste",
    "médicaments",
  ],
  entertainment: [
    "cinema ticket",
    "concert",
    "theatre show",
    "video game",
    "night out",
    "place de cinéma",
    "concert",
    "spectacle",
    "jeu vidéo",
  ],
  lodging: [
    "hotel night",
    "holiday accommodation",
    "the airbnb for the weekend",
    "campsite pitch",
    "mountain hut for the night",
    "nuit d'hôtel",
    "location de vacances",
    "le gîte pour le week-end",
    "emplacement de camping",
    "cabane pour la nuit",
  ],
  activities: [
    "museum entry",
    "guided tour of the old town",
    "ski pass for the day",
    "escape room with friends",
    "entry to the theme park",
    "entrée au musée",
    "visite guidée",
    "forfait de ski",
    "escape game entre amis",
    "entrée au parc d'attractions",
  ],
  subscriptions: [
    "monthly subscription",
    "streaming service",
    "annual membership",
    "cloud storage plan",
    "abonnement mensuel",
    "service de streaming",
    "adhésion annuelle",
  ],
  kids_family: [
    "childcare",
    "nursery fees",
    "babysitter",
    "the nanny",
    "pocket money for the children",
    "the care home",
    "garde d'enfants",
    "crèche",
    "la nounou",
    "argent de poche",
    "la maison de retraite",
  ],
  pets: [
    "pet food",
    "veterinarian",
    "dog grooming",
    "cat litter",
    "nourriture pour chien",
    "vétérinaire",
    "toilettage",
    "animalerie",
  ],
  gifts_donations: [
    "birthday present",
    "wedding gift",
    "charity donation",
    "flowers for someone",
    "cadeau d'anniversaire",
    "cadeau de mariage",
    "don à une association",
    "livraison de fleurs",
  ],
  insurance: [
    "the insurance premium",
    "home insurance",
    "car insurance",
    "health insurance",
    "life insurance",
    "la prime d'assurance",
    "assurance habitation",
    "assurance auto",
    "assurance maladie",
    "assurance vie",
  ],
  finance_admin: [
    "bank charges",
    "card fee",
    "currency conversion fee",
    "the tax bill",
    "the accountant's invoice",
    "renewing the passport",
    "the lawyer",
    "frais bancaires",
    "frais de carte",
    "frais de change",
    "les impôts",
    "la facture du comptable",
    "renouvellement du passeport",
    "l'avocat",
  ],
};
