import type { ExpenseCategory, SubcategoryOf } from "./types";

/**
 * Global category seed rules.
 *
 * This file is *data*. Adding a merchant or a phrase should never require
 * touching the classifier, and the classifier never hard-codes a brand.
 *
 * Phrases are grouped by language for maintenance only — matching is
 * language-agnostic, because a transaction does not say which language it is
 * in. A French speaker's card can perfectly well produce `MONTHLY RENT`.
 *
 * The four strengths, weakest to strongest:
 *
 *  - `weakKeywords`     a word that leans one way (`grill`, `mobilité`)
 *  - `ambiguousMerchants` a real brand that sells across categories
 *  - `merchantFragments`  a word that names the trade (`pharmacie`, `vet`)
 *  - `merchants`          a brand that means one category
 *  - `strongPhrases`      the activity said outright (`billet de train`)
 *
 * `excludes` suppresses a category's *text* evidence when a disqualifying
 * word is present — it never overrides a learned mapping or a merchant.
 *
 * Two things to know before adding a word:
 *
 *  - **Write the singular; the plural comes free.** Text is matched on
 *    singularised tokens, so `glace` covers `glaces` and `meuble` covers
 *    `meubles`. Only a trailing `s` or `x` comes off (see `singularize`), so
 *    an irregular plural is still its own entry. Merchants are *not* folded
 *    this way — a brand is a name.
 *  - **A word in two categories is a tie, not a hint.** Two 0.9 phrases
 *    cancel each other out on the margin rule and the field is left for the
 *    user to fill. Repeating a word across categories is therefore a
 *    deliberate statement that it really is ambiguous, not a way to cover
 *    both.
 *
 * See `docs/categorization.md` for how to extend any of this.
 */

/** Keyed by BCP-47 primary language subtag. Add a language by adding a key. */
export type PhrasesByLanguage = Readonly<Record<string, readonly string[]>>;

/**
 * A rule that names a *subcategory*, once the category is already settled.
 *
 * Held to a higher bar than a category rule, and it is the same bar the whole
 * feature rests on: a subcategory is only ever asserted when something named
 * it outright — a brand that sells one thing (`Shell` is fuel), or a phrase
 * that says it (`facture d'électricité`). There are no weak keywords here on
 * purpose. Being sure a purchase is `home` says nothing about which of its
 * twenty-four subcategories it is, and a plausible-looking guess filed under the
 * user's name is worse than the blank it replaced.
 *
 * Generic on the parent, so a rule cannot name a subcategory the category does
 * not have: `SubcategorySeed<"transport">` accepts `fuel` and rejects
 * `electricity` at compile time.
 */
export interface SubcategorySeed<C extends ExpenseCategory = ExpenseCategory> {
  readonly id: SubcategoryOf<C>;
  /** Brands, matched against the normalized merchant only. */
  readonly merchants?: readonly string[];
  /** The purchase said outright, in any language the file covers. */
  readonly phrases?: PhrasesByLanguage;
}

export interface CategorySeed {
  readonly id: ExpenseCategory;
  readonly strongPhrases: PhrasesByLanguage;
  readonly weakKeywords?: PhrasesByLanguage;
  /** Brands, matched against the normalized merchant only. */
  readonly merchants?: readonly string[];
  /** Trade words, matched anywhere in the normalized merchant. */
  readonly merchantFragments?: readonly string[];
  /** Brands that genuinely span categories: a hint, never a decision. */
  readonly ambiguousMerchants?: readonly string[];
  /** Words whose presence disqualifies this category's text evidence. */
  readonly excludes?: readonly string[];
  /**
   * Rules that refine this category into one of its subcategories. Optional
   * everywhere, and deliberately not exhaustive — a category with none simply
   * never suggests a second level, which is a supported outcome.
   */
  readonly subcategories?: readonly SubcategorySeed[];
}

export const CATEGORY_SEEDS: readonly CategorySeed[] = [
  {
    id: "groceries",
    strongPhrases: {
      en: [
        "kitkat",
        "kit kat",
        "bounty",
        "balisto",
        "ovomaltine",
        "caotina",
        "mentos",
        "tic tac",
        "chupa chups",
        "m and ms",
        "smarties",
        "ricola",
        "sugus",
        "petit ecolier",
        "belvita",
        "granola",
        "chocapic",
        "cheerios",
        "weetabix",
        "alpro",
        "oatly",
        "actimel",
        "yop",
        "danette",
        "yoplait",
        "la laitiere",
        "elle et vire",
        "kiri",
        "vache qui rit",
        "findus",
        "iglo",
        "bonduelle",
        "panzani",
        "herta",
        "fleury michon",
        "tipiak",
        "bjorg",
        "michel et augustin",
        "andros",
        "materne",
        "banania",
        "volvic",
        "badoit",
        "contrex",
        "cristaline",
        "valser",
        "aproz",
        "sinalco",
        "emmi",
        "cremo",
        "zweifel",
        "kambly",
        "oasis",
        "innocent",
        "1664",
        "groceries",
        "grocery store",
        "grocery shopping",
        "supermarket",
        "food shopping",
        "weekly groceries",
        "weekly shop",
        "food market",
        "convenience store",
        "organic grocery",
        "farmers market",
        "butcher",
        "butcher shop",
        "greengrocer",
        "fishmonger",
        "cheese shop",
        "food for the week",
        "household food",
        "bread",
        "milk",
        "eggs",
        "cheese",
        "butter",
        "yoghurt",
        "yogurt",
        "fruit",
        "fruits",
        "vegetables",
        "veggies",
        "pasta",
        "rice",
        "flour",
        "sugar",
        "cereal",
        "olive oil",
        "meat",
        "fish",
        "bottled water",
        "orange juice",
        "fruit juice",
        "food shop",
        "food run",
        "snacks for the week",
        "perrier",
        "evian",
        "vittel",
        "san pellegrino",
        "henniez",
        "rivella",
        "tropicana",
        "pringles",
        "doritos",
        "haribo",
        "kinder",
        "nutella",
        "oreo",
        "twix",
        "snickers",
        "toblerone",
        "lindt",
        "milka",
        "ferrero rocher",
        "barilla",
        "nesquik",
        "danone",
        "activia",
        "philadelphia",
        "babybel",
        "heinz",
        "kelloggs",
        "nescafé",
        "nespresso",
        "pepsi",
        "fuze tea",
        "fuzetea",
        "ice tea",
        "iced tea",
        "nestea",
        "sprite",
        "fanta",
        "orangina",
        "schweppes",
        "red bull",
        "redbull",
        "monster",
        "capri sun",
        "gatorade",
        "powerade",
        "heineken",
        "kronenbourg",
        "desperados",
        "corona",
        "guinness",
        "magnum",
        "cornetto",
        "feldschlösschen",
        "cardinal",
        "coca",
        "coca cola",
        "cola",
        "limonade",
      ],
      fr: [
        "courses",
        "courses alimentaires",
        "courses de la semaine",
        "supermarché",
        "hypermarché",
        "supérette",
        "épicerie",
        "épicerie bio",
        "marché alimentaire",
        "magasin alimentaire",
        "achat alimentaire",
        "alimentation",
        "boucherie",
        "poissonnerie",
        "fromagerie",
        "primeur",
        "au marché",
        "pain",
        "lait",
        "oeufs",
        "beurre",
        "fromage",
        "yaourt",
        "yaourts",
        "fruits",
        "légumes",
        "pâtes",
        "riz",
        "huile",
        "huile d'olive",
        "céréales",
        "viande",
        "poisson",
        "eau",
        "bouteille d'eau",
        "jus d'orange",
        "jus de fruits",
        "jus de pomme",
        "ravitaillement",
        "de quoi manger",
        "boulangerie",
        "pâtisserie",
        "viennoiseries",
      ],
    },
    weakKeywords: {
      en: [
        "market",
        "food",
        "fresh",
        "organic",
        "bio",
        "deli",
        "groceries",
        "shop",
      ],
      fr: [
        "farine",
        "sucre",
        "marché",
        "alimentation",
        "alimentaire",
        "frais",
        "bio",
        "vrac",
        "provisions",
      ],
    },
    merchants: [
      "migros",
      "migros m",
      "migros mm",
      "migros mmm",
      "migros online",
      "migros partner",
      "leshop",
      "coop supermarket",
      "coop city food",
      "coop alimentaire",
      "denner",
      "denner express",
      "aldi",
      "aldi suisse",
      "aldi france",
      "aldi nord",
      "aldi sud",
      "lidl",
      "carrefour",
      "carrefour market",
      "carrefour city",
      "carrefour contact",
      "carrefour express",
      "monoprix",
      "monop",
      "franprix",
      "e leclerc",
      "leclerc",
      "leclerc drive",
      "intermarché",
      "intermarche",
      "auchan",
      "casino",
      "spar",
      "volg",
      "manor food",
      "globus delicatessa",
      "picard",
      "super u",
      "hyper u",
      "u express",
      "grand frais",
      "biocoop",
      "naturalia",
      "satoriz",
      "la vie claire",
      "prodega",
      "aligro",
      "metro cash and carry",
      "farmy",
      "hellofresh",
      "gorillas",
      "flink",
      "getir",
      "picnic",
      "albert heijn",
      "delhaize",
      "colruyt",
      "rewe",
      "edeka",
      "kaufland",
      "netto",
      "penny markt",
      "mercadona",
      "esselunga",
      "conad",
      "tesco",
      "sainsbury",
      "waitrose",
    ],
    merchantFragments: [
      "supermarche",
      "supermarkt",
      "epicerie",
      "boucherie",
      "poissonnerie",
      "fromagerie",
      "superette",
      "grocery",
      "supermarket",
    ],
    excludes: [
      // A bill for something is not a trip to the shop, whatever it is for.
      "facture",
      "bill",
      "invoice",
      // Bread the group ate on the way is not bread for the flat.
      "pain au chocolat",
      "fish and chips",
      // English keeps a word for bread that French uses for suffering.
      "back pain",
      "neck pain",
      "chest pain",
      "joint pain",
      "period pain",
      "pain relief",
      "pain killer",
      "painkiller",
      "in pain",
      // And perfume is sold by the water.
      "eau de parfum",
      "eau de toilette",
      "eau de cologne",
    ],
    ambiguousMerchants: [
      // Forecourt and kiosk formats: groceries as often as fuel or a sandwich.
      "coop pronto",
      "migrolino",
      "avec",
      "shell select",
      "bp shop",
      "k kiosk",
      "aperto",
      "relay",
      // Bare "Coop" fronts a supermarket, a pharmacy and a filling station.
      "coop",
    ],
  },
  {
    id: "restaurants",
    strongPhrases: {
      en: [
        "restaurant",
        "cafe",
        "coffee shop",
        "bar",
        "pub",
        "bistro",
        "brasserie",
        "takeaway",
        "takeout",
        "food delivery",
        "lunch",
        "dinner",
        "breakfast",
        "brunch",
        "pizza",
        "burger",
        "sushi",
        "kebab",
        "tapas",
        "ramen",
        "poke bowl",
        "food truck",
        "street food",
        "bakery cafe",
        "fast food",
        "ice cream",
        "gelato",
        "frozen yogurt",
        "wine bar",
        "cocktail bar",
        "happy hour",
        "steakhouse",
        "meal out",
        "eating out",
        "drinks out",
        "coffee",
        "iced coffee",
        "hot chocolate",
        "milkshake",
        "smoothie",
        "waffle",
        "crepe",
        "pancakes",
        "donut",
        "doughnut",
        "churros",
        "cotton candy",
        "hot dog",
        "falafel",
        "shawarma",
        "noodles",
        "dim sum",
        "fish and chips",
        "chicken wings",
        "nachos",
        "beer",
        "wine",
        "cocktail",
        "drinks",
        "round of drinks",
        "take away",
        "snack bar",
        "food stand",
        "fries",
        "aperol",
        "aperol spritz",
        "spritz",
        "mojito",
        "ricard",
        "crisps and dips",
        "bakery",
        "pastry",
      ],
      fr: [
        "restaurant",
        "café",
        "bar",
        "bistrot",
        "bistro",
        "brasserie",
        "repas",
        "déjeuner",
        "dîner",
        "souper",
        "petit déjeuner",
        "brunch",
        "livraison de repas",
        "repas à emporter",
        "à emporter",
        "pizzeria",
        "sushi",
        "kebab",
        "crêperie",
        "fast-food",
        // In an expense, a "glace" is eaten. The ice and the mirror the word
        // also means are not things a group splits the cost of.
        "glace",
        "glaces",
        "glace italienne",
        "crème glacée",
        "cornet de glace",
        "apéro",
        "apéritif",
        "boire un verre",
        "resto",
        "au resto",
        "traiteur",
        "buvette",
        "restau",
        "bière",
        "vin",
        "verre de vin",
        "cocktail",
        "gaufre",
        "crêpe",
        "crêpes au sucre",
        "beignet",
        "churros",
        "barbe à papa",
        "chocolat chaud",
        "milkshake",
        "smoothie",
        "frites",
        "hamburger",
        "sandwich",
        "panini",
        "tacos",
        "falafel",
        "nouilles",
        "ramen",
        "hot dog",
        "croissant",
        "pain au chocolat",
        "viennoiserie",
        "boulangerie",
        "pâtisserie",
        "goûter",
        "casse-croûte",
        "terrasse",
        "en terrasse",
        "sur le pouce",
        "boisson",
        "boissons",
        "soda",
        "sirop",
      ],
    },
    weakKeywords: {
      en: [
        "kitchen",
        "grill",
        "pizza",
        "sushi",
        "burger",
        "bakery",
        "coffee",
        "espresso",
        "tea room",
        "beer",
        "beers",
        "wine",
        "cocktail",
        "cocktails",
        "tavern",
        "snack",
        "snacks",
        "cafeteria",
        "canteen",
        "brewery",
        "taco",
        "tacos",
        "barbecue",
        "bbq",
      ],
      fr: [
        "cuisine",
        "grill",
        "boulangerie",
        "pâtisserie",
        "café",
        "salon de thé",
        "bière",
        "bières",
        "vin",
        "vins",
        "cocktail",
        "cocktails",
        "taverne",
        "snack",
        "cantine",
        "manger",
        "sandwich",
        "sandwichs",
        "viennoiserie",
        "goûter",
      ],
    },
    merchants: [
      "o tacos",
      "otacos",
      "sushi shop",
      "planet sushi",
      "pizza express",
      "papa johns",
      "hippopotamus",
      "buffalo grill",
      "courtepaille",
      "flunch",
      "leon de bruxelles",
      "big mamma",
      "eataly",
      "columbus cafe",
      "segafredo",
      "illy",
      "krispy kreme",
      "cinnabon",
      "jeff de bruges",
      "la mie caline",
      "brioche doree",
      "class croute",
      "cojean",
      "exki",
      "dean and david",
      "hans im gluck",
      "nordsee",
      "caffe nero",
      "greggs",
      "itsu",
      "yo sushi",
      "paul",
      "pret",
      "quick",
      "mcdonald",
      "burger king",
      "kfc",
      "subway",
      "starbucks",
      "costa coffee",
      "tim hortons",
      "dunkin",
      "five guys",
      "domino",
      "dominos",
      "pizza hut",
      "taco bell",
      "chipotle",
      "nando",
      "pret a manger",
      "vapiano",
      "l osteria",
      "holy cow",
      "tibits",
      "hiltl",
      "manora",
      "autogrill",
      "brezelkonig",
      "brezelkönig",
      "coop restaurant",
      "migros restaurant",
      "uber eats",
      "ubereats",
      "deliveroo",
      "just eat",
      "justeat",
      "eat ch",
      "smood",
      "wolt",
      "glovo",
      "lieferando",
      "too good to go",
      "ben and jerry",
      "ben and jerrys",
      "ben and jerry s",
      "haagen dazs",
      "häagen dazs",
      "amorino",
      "movenpick glace",
      "mövenpick glace",
      "mcdo",
      "mcdonalds",
      "pret a manger",
      "dominos pizza",
      "wagamama",
      "sprüngli",
      "sprungli",
      "laduree",
      "ladurée",
      "movenpick",
      "mövenpick",
      "luigia",
      "gelateria",
      "creperie",
      "crêperie",
      "glacier",
    ],
    merchantFragments: [
      "restaurant",
      "ristorante",
      "trattoria",
      "osteria",
      "pizzeria",
      "brasserie",
      "bistrot",
      "taverne",
      "gelateria",
      "creperie",
      "crêperie",
      "kebab",
      "cafeteria",
    ],
    excludes: ["supermarket", "grocery", "supermarché"],
  },
  {
    id: "transport",
    strongPhrases: {
      en: [
        "public transport",
        "bus ticket",
        "train ticket",
        "metro ticket",
        "tram ticket",
        "travel pass",
        "monthly travel pass",
        "half fare",
        "taxi",
        "ride sharing",
        "rideshare",
        "car sharing",
        "parking",
        "car park",
        "parking fine",
        "toll",
        "motorway toll",
        "motorway vignette",
        "fuel",
        "petrol",
        "gasoline",
        "diesel",
        "charging station",
        "ev charging",
        "bike rental",
        "bike repair",
        "scooter rental",
        "car rental",
        "car wash",
        "car service",
        "roadside assistance",
        "bus",
        "tram",
        "metro",
        "underground",
        "ferry",
        "bike",
        "scooter",
        "vignette",
        "petrol station",
        "fuel up",
        "car purchase",
        "bought a car",
        "new car",
        "used car",
        "car dealership",
        "car leasing",
        "lease payment",
        "car loan",
        "car finance",
        "car repair",
        "garage repair",
        "mot test",
        "vehicle inspection",
        "tyres",
        "tires",
        "oil change",
        "vehicle registration",
        "road tax",
        "number plate",
      ],
      fr: [
        "transports publics",
        "transports en commun",
        "billet de train",
        "billet de bus",
        "billet de métro",
        "billet de tram",
        "abonnement général",
        "demi-tarif",
        "carte journalière",
        "taxi",
        "covoiturage",
        "autopartage",
        "parking",
        "stationnement",
        "amende de stationnement",
        "péage",
        "autoroute",
        "vignette autoroute",
        "essence",
        "carburant",
        "diesel",
        "borne de recharge",
        "recharge électrique",
        "location de vélo",
        "réparation vélo",
        "location de trottinette",
        "location de voiture",
        "lavage voiture",
        "révision voiture",
        "bus",
        "métro",
        "tram",
        "tramway",
        "ferry",
        "bateau",
        "vélo",
        "trottinette",
        "gasoil",
        "gazole",
        "vignette",
        "ticket de bus",
        "ticket de métro",
        "carte de transport",
        "plein d'essence",
        "faire le plein",
        "contrôle technique",
        "dépannage",
        "achat de voiture",
        "achat véhicule",
        "voiture neuve",
        "voiture d'occasion",
        "véhicule neuf",
        "véhicule d'occasion",
        "concession automobile",
        "leasing voiture",
        "mensualité leasing",
        "crédit auto",
        "prêt auto",
        "financement voiture",
        "réparation voiture",
        "garage automobile",
        "carrosserie",
        "pneus",
        "vidange",
        "immatriculation",
        "carte grise",
        "plaques d'immatriculation",
        "taxe véhicule",
        "impôt véhicule",
        "lavage auto",
        "station de lavage",
      ],
    },
    weakKeywords: {
      en: [
        "station",
        "mobility",
        "transport",
        "ticket",
        "transit",
        "garage",
        "bus",
        "train",
        "tram",
        "metro",
        "scooter",
        "tyres",
        "tires",
      ],
      fr: [
        "gare",
        "mobilité",
        "transport",
        "billet",
        "station",
        "garage",
        "bus",
        "train",
        "tram",
        "métro",
        "vélo",
        "trottinette",
        "pneus",
      ],
    },
    merchants: [
      // Garages and fast-fit chains. The category has to be reached before
      // `SUBCATEGORY_SEEDS` is ever consulted, so a brand that only appears
      // there names a subcategory of nothing.
      "midas",
      "norauto",
      "feu vert",
      "speedy",
      "kwik fit",
      "ats euromaster",
      "voi",
      "italo",
      "renfe",
      "car postal",
      "velib",
      "sbb",
      "cff",
      "ffs",
      "sbb cff ffs",
      "bls",
      "tpg",
      "tl lausanne",
      "transports publics genevois",
      "tpf",
      "vmcv",
      "cgn",
      "zvv",
      "rhb",
      "bernmobil",
      "vbz",
      "bvb",
      "carpostal",
      "postauto",
      "sncf",
      "sncf connect",
      "ouigo",
      "trainline",
      "omio",
      "eurostar",
      "thalys",
      "trenitalia",
      "italo treno",
      "deutsche bahn",
      "ratp",
      "tcl",
      "transdev",
      "flixbus",
      "blablacar",
      "alsa",
      "uber",
      "bolt",
      "free now",
      "freenow",
      "lime",
      "dott",
      "tier",
      "voi scooters",
      "swapfiets",
      "publibike",
      "mobility carsharing",
      "getaround",
      "easypark",
      "parkingpay",
      "indigo parking",
      "apcoa",
      "q park",
      "q-park",
      "vinci autoroutes",
      "sanef",
      "aprr",
      "europcar",
      "sixt",
      "hertz",
      "avis",
      "budget rent a car",
      "enterprise rent a car",
      "ionity",
      "chargepoint",
      "evpass",
      "shell recharge",
      "tesla supercharger",
    ],
    /**
     * Filling stations. Deliberately *not* plain merchants: half of what is
     * bought at one is a sandwich. `contextualOverrides` promotes them to a
     * decision as soon as the text mentions fuel.
     */
    ambiguousMerchants: [
      "shell",
      "bp",
      "esso",
      "avia",
      "tamoil",
      "migrol",
      "eni",
      "agrola",
      "socar",
      "tcs",
    ],
  },
  {
    id: "home",
    strongPhrases: {
      en: [
        "rent",
        "monthly rent",
        "apartment rent",
        "house rent",
        "rental payment",
        "landlord",
        "property management",
        "mortgage",
        "mortgage payment",
        "condominium fee",
        "hoa fee",
        "building maintenance",
        "tenant charge",
        "service charges",
        "rental deposit",
        "security deposit",
        "property tax",
        "council tax",
        "house purchase",
        "flat purchase",
        "property purchase",
        "down payment",
        "moving company",
        "removal company",
        "removal van",
        "self storage",
        "storage unit",
      ],
      fr: [
        "loyer",
        "loyer mensuel",
        "paiement du loyer",
        "régie immobilière",
        "régie",
        "bailleur",
        "bail",
        "hypothèque",
        "prêt hypothécaire",
        "charges de copropriété",
        "charges locatives",
        "entretien immeuble",
        "garantie de loyer",
        "caution loyer",
        "état des lieux",
        "taxe d'habitation",
        "taxe foncière",
        "dépôt de garantie",
        "caution du bail",
        "acquisition immobilière",
        "achat immobilier",
        "apport immobilier",
        "acompte immobilier",
        "déménagement",
        "déménageur",
        "camion de déménagement",
        "société de déménagement",
        "garde-meuble",
        "box de stockage",
      ],
    },
    weakKeywords: {
      en: ["apartment", "housing", "property", "building", "flat", "tenancy"],
      fr: [
        "appartement",
        "logement",
        "immeuble",
        "immobilier",
        "colocation",
        "coloc",
      ],
    },
    merchants: [
      "livit",
      "wincasa",
      "privera",
      "bernard nicod",
      "pilet renaud",
      "foncia",
      "nexity",
    ],
    merchantFragments: [
      "immobilier",
      "immobilière",
      "property management",
      "real estate management",
      "régie",
      "gérance",
      "gerance",
    ],
  },
  {
    id: "home",
    strongPhrases: {
      en: [
        "electricity bill",
        "electricity",
        "power bill",
        "gas bill",
        "natural gas",
        "water bill",
        "internet bill",
        "broadband",
        "mobile phone",
        "phone bill",
        "telecom",
        "heating",
        "district heating",
        "heating oil",
        "waste collection",
        "utilities",
        "tv licence",
        "meter reading",
        "mobile plan",
        "phone plan",
        "internet subscription",
        "water charges",
      ],
      fr: [
        "facture électricité",
        "électricité",
        "facture gaz",
        "gaz naturel",
        "facture eau",
        "facture d'eau",
        "internet",
        "fibre",
        "téléphonie",
        "téléphone",
        "abonnement mobile",
        "chauffage",
        "chauffage urbain",
        "mazout",
        "collecte des déchets",
        "taxe déchets",
        "services industriels",
        "redevance radio",
        "redevance tv",
        "relevé compteur",
        "gaz",
        "facture de gaz",
        "facture d'électricité",
        "facture internet",
        "forfait mobile",
        "forfait téléphonique",
        "abonnement internet",
        "box internet",
        "eau chaude",
      ],
    },
    weakKeywords: {
      en: ["energy", "telecom", "water", "broadband", "fiber", "fibre", "bill"],
      fr: ["énergie", "télécom", "eau", "fibre", "facture", "compteur"],
    },
    merchants: [
      "salt",
      "sosh",
      "totalenergies",
      "swisscom",
      "sunrise",
      "salt mobile",
      "wingo",
      "yallo",
      "lyca mobile",
      "lebara",
      "m budget mobile",
      "digitec connect",
      "init7",
      "quickline",
      "netplus",
      "vtx",
      "upc",
      "serafe",
      "billag",
      "sig geneve",
      "services industriels geneve",
      "viteos",
      "romande energie",
      "groupe e",
      "ewz",
      "iwb",
      "primeo energie",
      "bkw",
      "ckw",
      "axpo",
      "orange",
      "orange france",
      "sfr",
      "bouygues telecom",
      "free mobile",
      "free telecom",
      "edf",
      "engie",
      "veolia",
      "suez",
    ],
  },
  {
    id: "shopping",
    strongPhrases: {
      en: [
        "clothing",
        "clothes",
        "electronics",
        "online shopping",
        "department store",
        "shoes",
        "trainers",
        "accessories",
        "jewellery",
        "watch",
        "consumer electronics",
        "phone case",
        "headphones",
        "laptop",
        "bookshop",
        "stationery",
        "sports equipment",
      ],
      fr: [
        "vêtements",
        "habillement",
        "électronique",
        "achats en ligne",
        "grand magasin",
        "chaussures",
        "baskets",
        "accessoires",
        "bijoux",
        "montre",
        "casque audio",
        "ordinateur portable",
        "librairie",
        "papeterie",
        "matériel de sport",
      ],
    },
    weakKeywords: {
      en: ["clothes", "shoes", "outfit", "jacket", "shirt", "boutique"],
      fr: ["vêtement", "chaussure", "tenue", "veste", "pull", "boutique"],
    },
    merchants: [
      "gemo",
      "jules",
      "celio",
      "showroomprive",
      "refurbed",
      "galaxus",
      "digitec",
      "brack",
      "interdiscount",
      "melectronics",
      "microspot",
      "steg electronics",
      "back market",
      "backmarket",
      "h&m",
      "hm",
      "zara",
      "uniqlo",
      "mango",
      "c&a",
      "kiabi",
      "primark",
      "tally weijl",
      "chicoree",
      "chicorée",
      "zalando",
      "asos",
      "shein",
      "vinted",
      "veepee",
      "about you",
      "dosenbach",
      "ochsner sport",
      "sportxx",
      "athleticum",
      "decathlon",
      "intersport",
      "mediamarkt",
      "media markt",
      "fnac",
      "darty",
      "cdiscount",
      "temu",
      "aliexpress",
      "apple store",
      "samsung store",
      "globus",
      "loeb",
      "galeries lafayette",
      "printemps",
      "orell fussli",
      "payot librairie",
      "cultura",
    ],
    /**
     * Platforms, not shops. Amazon sells groceries, Apple sells subscriptions,
     * Manor runs a supermarket; `contextualOverrides` resolves the common
     * cases and everything else stays a suggestion.
     */
    ambiguousMerchants: ["amazon", "apple", "google", "manor"],
  },
  {
    id: "health",
    strongPhrases: {
      en: [
        "doctor",
        "physician",
        "medical",
        "hospital",
        "clinic",
        "pharmacy",
        "medication",
        "medicine",
        "prescription",
        "dentist",
        "dental",
        "orthodontist",
        "optician",
        "glasses",
        "contact lenses",
        "physiotherapy",
        "therapist",
        "therapy session",
        "laboratory",
        "medical test",
        "blood test",
        "vaccination",
        "consultation",
        "emergency room",
        "osteopath",
        "chiropractor",
        "hearing aid",
        "gym membership",
        "fitness club",
        "back pain",
        "neck pain",
        "therapeutic massage",
      ],
      fr: [
        "médecin",
        "médical",
        "hôpital",
        "clinique",
        "pharmacie",
        "médicament",
        "ordonnance",
        "dentiste",
        "dentaire",
        "orthodontiste",
        "opticien",
        "lunettes",
        "lentilles",
        "physiothérapie",
        "physiothérapeute",
        "thérapeute",
        "laboratoire",
        "analyse médicale",
        "prise de sang",
        "vaccination",
        "consultation",
        "urgences",
        "ostéopathe",
        "chiropracteur",
        "psychologue",
        "appareil auditif",
        "salle de sport",
        "abonnement salle de sport",
        "club de fitness",
        "mal de dos",
        "massage thérapeutique",
      ],
    },
    merchants: [
      "pharmacie plus",
      "doctolib",
      "optic 2000",
      "krys",
      "afflelou",
      "visilab",
      "amavita",
      "sun store",
      "sunstore",
      "coop vitality",
      "benu",
      "toppharm",
      "pharmacieplus",
      "galenica",
      "medbase",
      "hirslanden",
      "chuv",
      "hug",
      "unilabs",
      "synlab",
      "viollier",
    ],
    merchantFragments: [
      "pharmacie",
      "pharmacy",
      "apotheke",
      "pharma",
      "clinique",
      "clinic",
      "dental",
      "dentaire",
      "dentist",
      "dentiste",
      "medical",
      "médical",
      "optique",
      "optical",
      "optik",
      "laboratoire",
      "laboratory",
      "physio",
      "physiotherapie",
      "osteopathe",
      "hopital",
      "hôpital",
      "hospital",
      "permanence",
    ],
  },
  {
    id: "entertainment",
    strongPhrases: {
      en: [
        "cinema",
        "movie theatre",
        "movie theater",
        "theatre",
        "theater",
        "concert",
        "festival",
        "opera",
        "comedy show",
        "nightclub",
        "karaoke",
        "gaming",
        "video game",
        "game purchase",
        "event ticket",
        "gig ticket",
      ],
      fr: [
        "cinéma",
        "théâtre",
        "concert",
        "festival",
        "opéra",
        "spectacle",
        "discothèque",
        "boîte de nuit",
        "karaoké",
        "jeu vidéo",
        "jeux vidéo",
        "billet spectacle",
        "billet concert",
      ],
    },
    merchants: [
      "pathe",
      "pathé",
      "arena cinemas",
      "blue cinema",
      "cinepel",
      "ugc",
      "gaumont",
      "kinepolis",
      "ticketmaster",
      "ticketcorner",
      "starticket",
      "petzi",
      "eventim",
      "see tickets",
      "fnac spectacles",
      "steam",
      "playstation",
      "playstation network",
      "xbox",
      "nintendo",
      "epic games",
      "riot games",
      "blizzard",
      "humble bundle",
      "gog com",
    ],
    // A console store charging every month is a subscription, not an outing.
    excludes: ["monthly", "subscription", "abonnement"],
  },
  {
    /**
     * Flying, filed under `transport`.
     *
     * These rules used to be a category of their own called `travel`, which
     * named an occasion rather than a kind of spending: a flight, a hotel
     * night and a museum ticket are three different purchases that happen to
     * share a week. The flight half is transport and lives here; where people
     * slept is `lodging`, and what they did once there is `activities`.
     *
     * What did *not* come across is as deliberate as what did. "Travel
     * insurance", "visa fee" and "passport" are trip admin, not a journey;
     * `travel`, `holiday`, `vacances` and `séjour` say only that a trip
     * happened, and pointing them at `transport` would file a holiday dinner
     * as a bus fare. They are better unmatched than wrong.
     */
    id: "transport",
    strongPhrases: {
      en: [
        "airline",
        "plane ticket",
        "flight",
        "airfare",
        "airport transfer",
        "excess baggage",
        "seat selection",
      ],
      fr: [
        "compagnie aérienne",
        "billet d'avion",
        "vol",
        "navette aéroport",
        "bagage supplémentaire",
        "choix du siège",
      ],
    },
    weakKeywords: {
      en: ["flight", "airport"],
      fr: ["vol", "aéroport"],
    },
    merchants: [
      "easyjet",
      "swiss international",
      "swiss airlines",
      "edelweiss air",
      "ryanair",
      "air france",
      "klm",
      "lufthansa",
      "eurowings",
      "austrian airlines",
      "brussels airlines",
      "british airways",
      "iberia",
      "vueling",
      "transavia",
      "wizz air",
      "norwegian air",
      "tap portugal",
      "turkish airlines",
      "aegean airlines",
      "emirates",
      "qatar airways",
      "etihad",
      "singapore airlines",
      "cathay pacific",
      "air canada",
      "united airlines",
      "delta air lines",
      "american airlines",
    ],
    /**
     * The booking sites sell flights and hotel nights from the same basket,
     * and a package holiday is mostly the second. They suggest, they never
     * decide — which is what this bucket is for.
     */
    ambiguousMerchants: [
      "expedia",
      "opodo",
      "edreams",
      "lastminute",
      "kayak",
      "skyscanner",
      "kiwi com",
      "kuoni",
      "hotelplan",
      "tui",
      "club med",
      "secret escapes",
    ],
  },
  {
    id: "lodging",
    /**
     * Where the trip slept. Split out of `travel` so a week's rental stops
     * swallowing the getting-there, the eating and the doing.
     */
    strongPhrases: {
      en: [
        "hotel",
        "hotel night",
        "hostel",
        "accommodation",
        "vacation rental",
        "holiday rental",
        "holiday apartment",
        "guest house",
        "bed and breakfast",
        "room booking",
        "campsite",
        "camping pitch",
        "resort stay",
        "mountain hut",
        "check in",
      ],
      fr: [
        "hôtel",
        "nuit d'hôtel",
        "nuitée",
        "nuitées",
        "auberge",
        "auberge de jeunesse",
        "hébergement",
        "location de vacances",
        "logement de vacances",
        "chambre d'hôtes",
        "gîte",
        "chalet",
        "camping",
        "emplacement camping",
        "réservation hôtel",
        "refuge",
        "cabane",
        "location appartement",
        "appartement de vacances",
        "location saisonnière",
        "nuit d'hôtel",
        "nuits d'hôtel",
        "hôtel",
        "motel",
        "pension",
      ],
    },
    weakKeywords: {
      en: ["hotel", "hostel", "room", "rooms", "nights", "stay", "bnb"],
      fr: ["chambre", "nuit", "nuits", "gîte", "refuge", "auberge", "logement"],
    },
    merchants: [
      "hotels com",
      "ibis budget",
      "sheraton",
      "airbnb",
      "booking.com",
      "booking",
      "hotels.com",
      "hostelworld",
      "agoda",
      "trip.com",
      "vrbo",
      "abritel",
      "homeaway",
      "interhome",
      "e domizil",
      "swiss youth hostels",
      "accor",
      "ibis",
      "novotel",
      "mercure",
      "sofitel",
      "pullman",
      "marriott",
      "hilton",
      "hyatt",
      "radisson",
      "nh hotels",
      "premier inn",
      "travelodge",
      "campanile",
      "kyriad",
      "motel one",
      "citizenm",
      "25hours",
      "reka",
      "huttopia",
      "yelloh village",
      "center parcs",
      "landal",
      "pierre et vacances",
      "belambra",
      "odalys",
    ],
    merchantFragments: [
      "hotel",
      "hôtel",
      "hostel",
      "auberge",
      "camping",
      "motel",
      "guesthouse",
      "gasthof",
      "albergo",
      "pensione",
    ],
  },
  {
    id: "activities",
    /**
     * Tickets, tours and entries — the planned doing. Split out of
     * `entertainment`, which keeps the shows: a guided walk and a games
     * console were never the same line on a chart.
     */
    strongPhrases: {
      en: [
        "museum",
        "museum entry",
        "exhibition",
        "guided tour",
        "city tour",
        "sightseeing",
        "excursion",
        "day trip",
        "boat trip",
        "zoo",
        "aquarium",
        "theme park",
        "amusement park",
        "water park",
        "escape room",
        "escape game",
        "bowling",
        "mini golf",
        "ice skating",
        "diving",
        "kayaking",
        "canoeing",
        "paddleboarding",
        "climbing gym",
        "rafting",
        "ski lesson",
        "ski rental",
        "guided tour",
        "ski pass",
        "lift pass",
        "cable car",
        "climbing gym",
        "swimming pool",
        "wine tasting",
        "cooking class",
        "yoga class",
        "entrance fee",
        "entry ticket",
        "ski rental",
        "equipment rental",
      ],
      fr: [
        "musée",
        "entrée musée",
        "exposition",
        "visite guidée",
        "excursion",
        "randonnée",
        "parc d'attractions",
        "parc aquatique",
        "zoo",
        "aquarium",
        "escape game",
        "bowling",
        "mini golf",
        "patinoire",
        "forfait de ski",
        "forfait ski",
        "remontées mécaniques",
        "téléphérique",
        "salle d'escalade",
        "piscine",
        "dégustation",
        "cours de cuisine",
        "cours de yoga",
        "billet d'entrée",
        "droit d'entrée",
        "plongée",
        "kayak",
        "canoë",
        "paddle",
        "accrobranche",
        "via ferrata",
        "escalade",
        "parapente",
        "rafting",
        "snorkeling",
        "cours de ski",
        "location de skis",
        "entrée piscine",
        "match",
        "billet de match",
        "accrobranche",
        "karting",
        "laser game",
        "paintball",
        "location de skis",
        "location de matériel",
      ],
    },
    weakKeywords: {
      en: ["tour", "entry", "trail", "climbing", "hike", "fitness", "lesson"],
      fr: [
        "visite",
        "entrée",
        // "Sortie au restaurant" is Splitwise's own French for dining out, so
        // an outing is a hint here and never the answer.
        "sortie",
        "rando",
        "escalade",
        "ski",
        "parc",
        "atelier",
        "fitness",
        "cours",
      ],
    },
    merchants: [
      "europapark",
      "europa park",
      "disneyland",
      "parc asterix",
      "walibi",
      "aquaparc",
      "alpamare",
      "connyland",
      "swiss vapeur parc",
      "papiliorama",
      "verkehrshaus",
      "musee olympique",
      "chaplin s world",
      "jungfraujoch",
      "glacier 3000",
      "titlis",
      "gornergrat",
      "rochers de naye",
      "magic pass",
      "getyourguide",
      "viator",
      "tiqets",
      "klook",
      "civitatis",
    ],
    excludes: [
      // An outing bought for somebody is a present, and the word for it is
      // right there in the description. Without this, adding a sport to the
      // vocabulary silently un-decided every gift that named one.
      "cadeau",
      "cadeaux",
      "gift",
      "present for",
      "carte cadeau",
      "bon cadeau",
    ],
    merchantFragments: [
      "musee",
      "musée",
      "museum",
      "zoo",
      "aquarium",
      "patinoire",
      "bowling",
      "karting",
      "escalade",
      "fitness",
      "piscine",
    ],
  },
  {
    id: "home",
    /**
     * The upkeep of where people live: supplies, furniture, repairs. It used
     * to scatter between `shopping` (a thing was bought) and `housing` (the
     * flat was involved), which is why neither total meant anything.
     */
    strongPhrases: {
      en: [
        "household supplies",
        "cleaning products",
        "cleaning supplies",
        "laundry detergent",
        "toilet paper",
        "kitchen supplies",
        "kitchenware",
        "furniture",
        "home goods",
        "home decor",
        "hardware store",
        "diy store",
        "light bulbs",
        "garden centre",
        "gardening",
        "home repair",
        "appliance",
        "appliance repair",
        "plumber",
        "electrician",
        "handyman",
        "cleaning service",
        "moving boxes",
        "storage unit",
        "bed linen",
        "crockery",
        "sponges",
        "bin bags",
        "rubbish bags",
        "batteries",
        "curtains",
        "drill",
        "vacuum cleaner",
        "broom",
        "towels",
        "coat hangers",
      ],
      fr: [
        "produits ménagers",
        "produits d'entretien",
        "produits de nettoyage",
        "lessive",
        "papier toilette",
        "papier ménage",
        "vaisselle",
        "ustensiles de cuisine",
        "meubles",
        "mobilier",
        "décoration",
        "électroménager",
        "bricolage",
        "outils",
        "quincaillerie",
        "ampoules",
        "jardinage",
        "jardinerie",
        "éponges",
        "sacs poubelle",
        "sac poubelle",
        "piles",
        "rideaux",
        "perceuse",
        "visserie",
        "serviettes",
        "torchons",
        "cintres",
        "aspirateur",
        "balai",
        "produits ménage",
        "réparation maison",
        "plombier",
        "électricien",
        "serrurier",
        "femme de ménage",
        "service de nettoyage",
        "déménagement",
        "garde-meuble",
        "literie",
        "linge de maison",
      ],
    },
    weakKeywords: {
      en: [
        "cleaning",
        "detergent",
        "furniture",
        "garden",
        "tools",
        "repair",
        "diy",
        "hardware",
      ],
      fr: [
        "ménage",
        "entretien",
        "meuble",
        "meubles",
        "jardin",
        "outils",
        "réparation",
        "déco",
      ],
    },
    merchants: [
      "ikea",
      "conforama",
      "maisons du monde",
      "jumbo",
      "hornbach",
      "obi",
      "bauhaus",
      "brico depot",
      "bricorama",
      "leroy merlin",
      "castorama",
      "coop bau hobby",
      "coop bau und hobby",
      "do it garden",
      "migros do it",
      "landi",
      "jysk",
      "kave home",
      "westwing",
      "micasa",
      "interio",
      "pfister",
      "livique",
      "lipo",
      "ottos",
      "casa",
      "zara home",
      "flying tiger",
      "sostrene grene",
      "gifi",
      "centrakor",
      "botanic",
      "truffaut",
      "jardiland",
      "gamm vert",
      "schilliger",
    ],
    merchantFragments: [
      "quincaillerie",
      "droguerie",
      "jardinerie",
      "bricolage",
      "brico",
      "ameublement",
      "nettoyage",
      "plomberie",
    ],
    // Sells food, toys and cleaning products in the same basket.
    ambiguousMerchants: ["action"],
  },
  {
    id: "subscriptions",
    strongPhrases: {
      en: [
        "subscription",
        "monthly subscription",
        "annual subscription",
        "membership",
        "recurring subscription",
        "premium plan",
        "monthly plan",
        "yearly plan",
        "auto renewal",
        "family plan",
      ],
      fr: [
        "abonnement",
        "abonnement mensuel",
        "abonnement annuel",
        "adhésion",
        "cotisation",
        "cotisation annuelle",
        "paiement récurrent",
        "renouvellement",
        "forfait premium",
        "forfait mensuel",
        "forfait annuel",
      ],
    },
    /**
     * Recurrence is not a kind of spending.
     *
     * "Abonnement", "forfait" and "renouvellement" sit in front of half the
     * regular payments a household makes, and most of those have a category
     * that says what was actually bought: the gym is `health`, a season
     * ticket is `transport`, the phone plan is `home`, a passport is
     * `finance_admin`. When one of those words is present this category's
     * *text* evidence stands down and lets it win — the brands below are
     * unaffected, so Netflix is Netflix however the row is described.
     */
    excludes: [
      "salle de sport",
      "gym",
      "fitness club",
      "club de fitness",
      "transports en commun",
      "transports publics",
      "abonnement général",
      "demi-tarif",
      "travel pass",
      "season ticket",
      "forfait mobile",
      "mobile plan",
      "phone plan",
      "passeport",
      "passport",
      "visa",
      "assurance",
      "insurance",
    ],
    merchants: [
      "prime video",
      "apple tv",
      "canal plus",
      "twitch",
      "kindle unlimited",
      "proton",
      "netflix",
      "spotify",
      "disney plus",
      "disney+",
      "hbo max",
      "paramount plus",
      "crunchyroll",
      "mubi",
      "youtube premium",
      "youtube music",
      "apple music",
      "icloud",
      "apple.com/bill",
      "google one",
      "google storage",
      "amazon prime",
      "audible",
      "deezer",
      "tidal",
      "storytel",
      "adobe",
      "creative cloud",
      "microsoft 365",
      "office 365",
      "dropbox",
      "notion",
      "evernote",
      "canva",
      "figma",
      "github",
      "openai",
      "anthropic",
      "midjourney",
      "perplexity",
      "google workspace",
      "protonmail",
      "proton ag",
      "nordvpn",
      "expressvpn",
      "1password",
      "bitwarden",
      "backblaze",
      "duolingo",
      "strava",
      "patreon",
      "substack",
      "linkedin premium",
      "le monde",
      "mediapart",
      "le temps",
      "24 heures",
      "tribune de geneve",
      "nzz",
      "nytimes",
      "new york times",
      "the guardian",
      "the economist",
      "financial times",
    ],
    // "Max" alone is a first name far more often than it is the streaming
    // service, so it only ever hints; "hbo max" above is the real rule.
    ambiguousMerchants: ["max"],
  },
  {
    id: "kids_family",
    strongPhrases: {
      en: [
        "childcare",
        "daycare",
        "nursery",
        "babysitter",
        "babysitting",
        "nanny",
        "child care",
        "nappies",
        "diapers",
        "baby formula",
        "elder care",
        "care home",
        "nursing home",
        "home carer",
        "child support",
        "maintenance payment",
        "pocket money",
      ],
      fr: [
        "garde d'enfant",
        "garde enfants",
        "crèche",
        "garderie",
        "nounou",
        "maman de jour",
        "baby-sitter",
        "babysitting",
        "couches",
        "lait infantile",
        "poussette",
        "aide à domicile",
        "maison de retraite",
        "ehpad",
        "aide aux personnes âgées",
        "pension alimentaire",
        "argent de poche",
      ],
    },
    merchants: ["orchestra premaman"],
    merchantFragments: [
      "crèche",
      "creche",
      "nursery",
      "garderie",
      "childcare",
      "kita",
      "kinderkrippe",
      "uape",
      "ehpad",
    ],
  },
  {
    id: "pets",
    strongPhrases: {
      en: [
        "pet",
        "pet food",
        "dog food",
        "cat food",
        "cat litter",
        "veterinarian",
        "veterinary",
        "vet",
        "pet grooming",
        "animal hospital",
        "pet insurance",
        "pet store",
        "dog boarding",
        "dog walker",
        "microchip",
      ],
      fr: [
        "animal",
        "animaux",
        "nourriture animaux",
        "nourriture chien",
        "nourriture chat",
        "croquettes",
        "litière",
        "vétérinaire",
        "clinique vétérinaire",
        "toilettage",
        "assurance animaux",
        "animalerie",
        "pension pour chien",
        "promeneur de chien",
        "puce électronique",
      ],
    },
    weakKeywords: {
      en: ["dog", "cat", "puppy", "kitten", "pets"],
      fr: ["chien", "chat", "chiot", "chaton", "animalier"],
    },
    merchants: [
      "whiskas",
      "pedigree",
      "purina",
      "zooplus",
      "bitiba",
      "fressnapf",
      "maxi zoo",
      "qualipet",
      "animalis",
      "tom and co",
      "royal canin",
    ],
    merchantFragments: [
      "vet",
      "veterinary",
      "vétérinaire",
      "veterinaire",
      "pet",
      "animalerie",
    ],
  },
  {
    id: "gifts_donations",
    strongPhrases: {
      en: [
        "gift",
        "present",
        "birthday present",
        "wedding gift",
        "gift card",
        "gift voucher",
        "donation",
        "charity",
        "charitable donation",
        "fundraiser",
        "flowers delivery",
        "leaving gift",
        "flowers",
        "bouquet",
        "florist",
      ],
      fr: [
        "cadeau",
        "cadeau anniversaire",
        "cadeau mariage",
        "carte cadeau",
        "bon cadeau",
        "don",
        "donation",
        "association caritative",
        "œuvre caritative",
        "collecte de fonds",
        "livraison de fleurs",
        "pot de départ",
        "fleurs",
        "bouquet",
        "bouquet de fleurs",
        "fleuriste",
        "cadeaux",
      ],
    },
    merchants: [
      "interflora",
      "fleurop",
      "aquarelle",
      "bergamotte",
      "monceau fleurs",
      "unicef",
      "red cross",
      "croix rouge",
      "médecins sans frontières",
      "medecins sans frontieres",
      "msf",
      "wwf",
      "greenpeace",
      "amnesty international",
      "caritas",
      "terre des hommes",
      "handicap international",
      "restos du coeur",
      "gofundme",
      "helloasso",
      "leetchi",
    ],
    merchantFragments: [
      "charity",
      "donation",
      "fondation",
      "foundation",
      "association",
      "fleuriste",
      "florist",
    ],
  },
  {
    id: "finance_admin",
    strongPhrases: {
      en: [
        "bank fee",
        "banking fee",
        "account fee",
        "card fee",
        "credit card fee",
        "debit card fee",
        "atm fee",
        "withdrawal fee",
        "exchange fee",
        "foreign exchange fee",
        "conversion fee",
        "service fee",
        "transaction fee",
        "late fee",
        "administration fee",
        "processing fee",
        "interest charged",
        "overdraft fee",
        "penalty",
        "fine",
        "speeding ticket",
        "income tax",
        "tax return",
        "tax bill",
        "vat payment",
        "loan repayment",
        "loan instalment",
        "accountant",
        "bookkeeping",
        "lawyer",
        "solicitor",
        "notary",
        "legal fee",
        "passport renewal",
        "visa application",
        "residence permit",
        "id card",
      ],
      fr: [
        "frais bancaires",
        "frais de compte",
        "frais de carte",
        "frais carte bancaire",
        "frais de retrait",
        "frais de change",
        "frais de conversion",
        "frais de service",
        "frais de transaction",
        "frais de retard",
        "frais administratifs",
        "frais de dossier",
        "frais de traitement",
        "intérêts débiteurs",
        "frais de découvert",
        "agios",
        "droit de timbre",
        "amende",
        "contravention",
        "impôt sur le revenu",
        "déclaration d'impôts",
        "tva",
        "remboursement de prêt",
        "mensualité de prêt",
        "comptable",
        "expert-comptable",
        "avocat",
        "notaire",
        "frais de justice",
        "renouvellement passeport",
        "demande de visa",
        "permis de séjour",
        "carte d'identité",
      ],
    },
    merchants: ["impots gouv", "greffe"],
    merchantFragments: [
      "fee",
      "fees",
      "commission",
      "frais",
      "surcharge",
      "avocat",
      "notaire",
      "fiduciaire",
      "comptable",
    ],
  },
  {
    /**
     * What is done *to a person* rather than bought as a thing.
     *
     * These rules were `shopping`'s until the split, which is why the shops
     * came with them: Sephora sells the same lipstick a department store
     * does, and the difference the taxonomy draws is what the money was for.
     */
    id: "personal_care",
    strongPhrases: {
      en: [
        "haircut",
        "hairdresser",
        "hair salon",
        "barber",
        "nail salon",
        "manicure",
        "pedicure",
        "beauty salon",
        "beautician",
        "cosmetics",
        "perfume",
        "make up",
        "skincare",
        "facial",
        "waxing",
        "toiletries",
        "shampoo",
        "spa day",
        "massage",
        "hammam",
        "sauna",
        "dry cleaning",
        "dry cleaner",
        "laundrette",
        "laundromat",
      ],
      fr: [
        "coiffeur",
        "salon de coiffure",
        "coupe de cheveux",
        "barbier",
        "manucure",
        "pédicure",
        "institut de beauté",
        "esthéticienne",
        "cosmétiques",
        "parfum",
        "maquillage",
        "soin du visage",
        "épilation",
        "produits d'hygiène",
        "shampoing",
        "spa",
        "massage",
        "hammam",
        "sauna",
        "pressing",
        "blanchisserie",
        "laverie",
      ],
    },
    weakKeywords: {
      en: ["salon", "grooming", "cosmetic"],
      fr: ["coiffure", "beauté", "esthétique"],
    },
    merchants: [
      "sephora",
      "marionnaud",
      "douglas",
      "douglas parfumerie",
      "nocibe",
      "yves rocher",
      "the body shop",
      "rituals",
      "lush",
      "kiehls",
      "nocibé",
    ],
    merchantFragments: [
      "coiffure",
      "coiffeur",
      "barbershop",
      "barbier",
      "hairdresser",
      "parfumerie",
      "pressing",
      "esthetique",
      "esthétique",
      "nagelstudio",
    ],
    /**
     * A massage from a physiotherapist is health, and a therapeutic one is
     * prescribed. The word alone is not enough to tell the salon from the
     * clinic, so a medical marker takes this category's text evidence away.
     */
    excludes: [
      "physio",
      "physiothérapie",
      "kiné",
      "kinésithérapie",
      "ordonnance",
      "pain",
      "douleur",
      "dos",
      "thérapeutique",
      "therapeutic",
    ],
  },
  {
    /**
     * Learning, whoever is doing it.
     *
     * The school rules arrived from `kids_family`, which had made them a fact
     * about the pupil. An evening language course and a child's termly fees
     * are the same purchase, so they are one code now and the age of the
     * student is not part of it.
     */
    id: "education",
    strongPhrases: {
      en: [
        "tuition",
        "tuition fee",
        "school fee",
        "school lunch",
        "school trip",
        "school supplies",
        "university fee",
        "semester fee",
        "enrolment fee",
        "language course",
        "evening class",
        "online course",
        "training course",
        "professional training",
        "certification",
        "driving lessons",
        "driving school",
        "music lesson",
        "swimming lessons",
        "private tutor",
        "tutoring",
        "textbook",
        "school books",
        "exam fee",
        "exam registration",
      ],
      fr: [
        "frais de scolarité",
        "frais scolaires",
        "écolage",
        "cantine scolaire",
        "sortie scolaire",
        "fournitures scolaires",
        "frais universitaires",
        "frais d'inscription",
        "cours de langue",
        "cours du soir",
        "cours en ligne",
        "formation professionnelle",
        "formation continue",
        "auto-école",
        "leçon de conduite",
        "cours de musique",
        "cours de natation",
        "parascolaire",
        "soutien scolaire",
        "cours particulier",
        "manuel scolaire",
        "livre scolaire",
        "frais d'examen",
      ],
    },
    weakKeywords: {
      en: ["course", "lesson", "class", "school", "student"],
      fr: ["cours", "leçon", "scolaire", "étudiant", "formation"],
    },
    merchants: [
      "coursera",
      "udemy",
      "edx",
      "openclassrooms",
      "duolingo",
      "babbel",
      "berlitz",
      "wall street english",
      "kumon",
    ],
    merchantFragments: [
      "école",
      "ecole",
      "school",
      "universite",
      "université",
      "university",
      "college",
      "collège",
      "gymnase",
      "lycee",
      "lycée",
      "academy",
      "academie",
      "académie",
      "hochschule",
      "auto ecole",
      "formation",
    ],
  },
  {
    /**
     * Premiums, wherever the policy points.
     *
     * The health insurers came from `health` and the flat's cover from
     * `home`; the car's had no code at all. Reading the *policy* out of the
     * text is what the subcategory rules do — this level only has to know
     * that a premium was paid.
     *
     * `pets` is deliberately not covered: an animal's insurance stays with
     * the animal, see `taxonomy.ts`.
     */
    id: "insurance",
    strongPhrases: {
      en: [
        "insurance premium",
        "insurance policy",
        "home insurance",
        "contents insurance",
        "building insurance",
        "tenant insurance",
        "car insurance",
        "vehicle insurance",
        "motor insurance",
        "health insurance",
        "life insurance",
        "travel insurance",
        "liability insurance",
        "legal expenses insurance",
        "legal protection insurance",
        "income protection",
        "disability insurance",
      ],
      fr: [
        "prime d'assurance",
        "police d'assurance",
        "assurance habitation",
        "assurance ménage",
        "assurance logement",
        "assurance auto",
        "assurance automobile",
        "assurance véhicule",
        "assurance maladie",
        "caisse maladie",
        "prime maladie",
        "assurance vie",
        "assurance voyage",
        "responsabilité civile",
        "protection juridique",
        "assurance invalidité",
        "prévoyance",
      ],
    },
    weakKeywords: {
      en: ["insurance", "premium", "policy", "cover"],
      fr: ["assurance", "prime", "police", "mutuelle"],
    },
    merchants: [
      "groupe mutuel",
      "css assurance",
      "helsana",
      "swica",
      "sanitas",
      "visana",
      "concordia",
      "assura",
      "atupri",
      "sympany",
      "harmonie mutuelle",
      "axa",
      "allianz",
      "generali",
      "zurich assurance",
      "mobiliere",
      "mobilière",
      "baloise",
      "vaudoise",
      "maif",
      "macif",
      "matmut",
      "gmf",
      "maaf",
      "groupama",
      "direct assurance",
      "luko",
      "smabtp",
    ],
    merchantFragments: [
      "assurance",
      "assurances",
      "versicherung",
      "insurance",
      "mutuelle",
      "krankenkasse",
    ],
    /**
     * `pet insurance` and its French spelling belong to `pets`, and a claim
     * *reimbursement* is money coming back rather than a premium going out.
     */
    excludes: [
      "pet insurance",
      "assurance animaux",
      "assurance chien",
      "assurance chat",
      "remboursement",
      "reimbursement",
    ],
  },
  /**
   * `other` carries no evidence at all, by design. It is where the classifier
   * lands when nothing else does, never something it can be argued into.
   */
  { id: "other", strongPhrases: {} },
];

/**
 * Why a category may appear more than once above.
 *
 * `home` is three entries, not one: the rules that were `housing`, `utilities`
 * and `household` kept their shape when the codes merged. Leaving them apart
 * is deliberate, and it is about `excludes`, which are scoped to the entry
 * that declares them — the bill rules can disqualify themselves on a word
 * without also silencing the furniture rules. Folding the three lists into one
 * would union those exclusions and quietly blind the category to two thirds of
 * its own evidence.
 *
 * Scoring is unaffected by the repetition: signals are grouped, and a group
 * contributes its strongest member once (see `confidence.ts`), so three
 * entries agreeing on `home` score exactly what one would. What the merge does
 * change is that they can no longer *disagree*: a word both `housing` and
 * `household` claimed used to be a tie that cancelled itself out on the margin
 * rule, and is now simply `home`.
 *
 * `transport` is two entries for the same reason — the flight rules arrived
 * from the retired `travel` code.
 */
export const SEED_BY_CATEGORY: ReadonlyMap<ExpenseCategory, CategorySeed> =
  new Map(
    CATEGORY_SEEDS.reduce<[ExpenseCategory, CategorySeed][]>((merged, seed) => {
      const existing = merged.find(([id]) => id === seed.id);
      if (!existing) {
        merged.push([seed.id, seed]);
        return merged;
      }
      existing[1] = mergeSeeds(existing[1], seed);
      return merged;
    }, []),
  );

/** Union of two seeds for one category. Used only by `SEED_BY_CATEGORY`. */
function mergeSeeds(a: CategorySeed, b: CategorySeed): CategorySeed {
  const languages = new Set([
    ...Object.keys(a.strongPhrases),
    ...Object.keys(b.strongPhrases),
    ...Object.keys(a.weakKeywords ?? {}),
    ...Object.keys(b.weakKeywords ?? {}),
  ]);

  const mergePhrases = (
    left: PhrasesByLanguage | undefined,
    right: PhrasesByLanguage | undefined,
  ): PhrasesByLanguage =>
    Object.fromEntries(
      [...languages]
        .map((language) => [
          language,
          [
            ...new Set([
              ...(left?.[language] ?? []),
              ...(right?.[language] ?? []),
            ]),
          ],
        ])
        .filter(([, phrases]) => phrases.length > 0),
    );

  const mergeList = (
    left: readonly string[] | undefined,
    right: readonly string[] | undefined,
  ): readonly string[] | undefined => {
    const all = [...new Set([...(left ?? []), ...(right ?? [])])];
    return all.length > 0 ? all : undefined;
  };

  return {
    id: a.id,
    strongPhrases: mergePhrases(a.strongPhrases, b.strongPhrases),
    weakKeywords: mergePhrases(a.weakKeywords, b.weakKeywords),
    merchants: mergeList(a.merchants, b.merchants),
    merchantFragments: mergeList(a.merchantFragments, b.merchantFragments),
    ambiguousMerchants: mergeList(a.ambiguousMerchants, b.ambiguousMerchants),
    excludes: mergeList(a.excludes, b.excludes),
  };
}

/** Every phrase of a bucket, across languages. */
export function allPhrases(
  phrases: PhrasesByLanguage | undefined,
): readonly string[] {
  if (!phrases) return [];
  return Object.values(phrases).flat();
}

/**
 * The second level, keyed by the category it refines.
 *
 * Separate from `CATEGORY_SEEDS` rather than nested inside each entry, for the
 * reason given above `SEED_BY_CATEGORY`: `home` and `transport` are each
 * several entries, and hanging subcategory rules off one of them would make
 * which entry an arbitrary and load-bearing choice.
 *
 * The mapped type is what keeps the two levels honest — every key must be a
 * real category, and every `id` under it must be one of *that* category's
 * subcategories. `groceries: [{ id: "fuel" }]` does not compile.
 *
 * Coverage is intentionally partial. These are the merchants and phrases that
 * name a subcategory beyond argument; everything else leaves the field blank
 * for the user, which is a complete answer and not a failure.
 */
export const SUBCATEGORY_SEEDS: {
  readonly [C in ExpenseCategory]?: readonly SubcategorySeed<C>[];
} = {
  groceries: [
    {
      id: "supermarket",
      merchants: [
        "carrefour",
        "lidl",
        "aldi",
        "migros",
        "coop",
        "denner",
        "leclerc",
        "intermarche",
        "auchan",
        "casino",
        "monoprix",
        "franprix",
        "super u",
        "hyper u",
        "cora",
        "delhaize",
        "colruyt",
        "albert heijn",
        "tesco",
        "sainsburys",
        "mercadona",
        "edeka",
        "rewe",
        "kaufland",
      ],
      phrases: { en: ["supermarket"], fr: ["supermarché"] },
    },
    { id: "bakery", phrases: { en: ["bakery"], fr: ["boulangerie"] } },
    { id: "butcher", phrases: { en: ["butcher"], fr: ["boucherie"] } },
    {
      id: "market",
      phrases: { en: ["farmers market"], fr: ["marché du samedi"] },
    },
  ],
  restaurants: [
    {
      id: "food_delivery",
      merchants: [
        "uber eats",
        "deliveroo",
        "just eat",
        "smood",
        "eat ch",
        "doordash",
        "glovo",
      ],
      phrases: { en: ["food delivery"], fr: ["livraison de repas"] },
    },
    {
      id: "fast_food",
      merchants: [
        "mcdonalds",
        "burger king",
        "kfc",
        "subway",
        "quick",
        "five guys",
      ],
      phrases: { en: ["fast food"], fr: ["restauration rapide"] },
    },
    {
      id: "cafe",
      merchants: ["starbucks", "costa coffee", "pret a manger"],
      phrases: { en: ["coffee shop"], fr: ["salon de thé"] },
    },
    { id: "takeaway", phrases: { en: ["takeaway"], fr: ["à emporter"] } },
  ],
  transport: [
    {
      id: "fuel",
      merchants: [
        "shell",
        "esso",
        "total",
        "totalenergies",
        "bp",
        "avia",
        "socar",
        "tamoil",
        "agip",
        "eni",
        "aral",
        "q8",
      ],
      phrases: { en: ["petrol", "fuel"], fr: ["carburant", "essence"] },
    },
    {
      id: "taxi_ride_hailing",
      merchants: ["uber", "bolt", "lyft", "freenow", "g7"],
      phrases: { en: ["taxi"], fr: ["taxi", "vtc"] },
    },
    {
      id: "train",
      merchants: ["sncf", "cff", "sbb", "ouigo", "trenitalia", "renfe", "db"],
      phrases: { en: ["train ticket"], fr: ["billet de train"] },
    },
    {
      id: "flights",
      merchants: [
        "easyjet",
        "ryanair",
        "air france",
        "swiss international",
        "lufthansa",
        "klm",
        "british airways",
        "wizz air",
        "vueling",
      ],
      phrases: { en: ["flight", "plane ticket"], fr: ["billet d'avion"] },
    },
    { id: "parking", phrases: { en: ["parking"], fr: ["stationnement"] } },
    { id: "tolls", phrases: { en: ["toll"], fr: ["péage"] } },
    {
      id: "car_rental",
      merchants: ["hertz", "avis", "sixt", "europcar", "enterprise rent"],
      phrases: { en: ["car rental"], fr: ["location de voiture"] },
    },
    {
      id: "public_transport",
      phrases: { en: ["public transport"], fr: ["transports en commun"] },
    },
    {
      id: "vehicle_maintenance",
      merchants: [
        "midas",
        "norauto",
        "feu vert",
        "speedy",
        "kwik fit",
        "ats euromaster",
        "pneus online",
      ],
      phrases: {
        en: ["car repair", "garage repair", "oil change", "vehicle inspection"],
        fr: [
          "réparation voiture",
          "garage automobile",
          "vidange",
          "contrôle technique",
        ],
      },
    },
    {
      id: "vehicle_purchase",
      phrases: {
        en: ["car purchase", "bought a car", "car dealership"],
        fr: [
          "achat de voiture",
          "achat véhicule",
          "voiture neuve",
          "voiture d'occasion",
          "véhicule neuf",
          "concession automobile",
        ],
      },
    },
    {
      id: "vehicle_lease",
      phrases: {
        en: ["car leasing", "lease payment"],
        fr: ["leasing voiture", "mensualité leasing"],
      },
    },
    {
      id: "vehicle_financing",
      phrases: {
        en: ["car loan", "car finance"],
        fr: ["crédit auto", "prêt auto", "financement voiture"],
      },
    },
    {
      id: "vehicle_registration",
      phrases: {
        en: ["vehicle registration", "road tax"],
        fr: ["carte grise", "immatriculation"],
      },
    },
    {
      id: "vehicle_wash",
      phrases: { en: ["car wash"], fr: ["lavage auto", "station de lavage"] },
    },
  ],
  home: [
    {
      id: "electricity",
      merchants: ["edf", "engie", "romande energie", "sig", "ewz"],
      phrases: { en: ["electricity bill"], fr: ["facture d'électricité"] },
    },
    { id: "water", phrases: { en: ["water bill"], fr: ["facture d'eau"] } },
    { id: "gas", phrases: { en: ["gas bill"], fr: ["facture de gaz"] } },
    {
      id: "internet",
      merchants: ["swisscom", "sunrise", "salt", "free", "orange", "bouygues"],
      phrases: { en: ["internet bill"], fr: ["abonnement internet"] },
    },
    {
      id: "mobile_phone",
      phrases: { en: ["mobile plan"], fr: ["forfait mobile"] },
    },
    { id: "rent", phrases: { en: ["rent"], fr: ["loyer"] } },
    { id: "mortgage", phrases: { en: ["mortgage"], fr: ["prêt immobilier"] } },
    {
      id: "furniture",
      merchants: ["ikea", "micasa", "conforama", "but", "maisons du monde"],
      phrases: { en: ["furniture"], fr: ["mobilier"] },
    },
    {
      id: "appliances",
      phrases: { en: ["appliance"], fr: ["électroménager"] },
    },
    {
      id: "repairs",
      phrases: {
        en: ["plumber", "electrician"],
        fr: ["plombier", "électricien"],
      },
    },
    {
      id: "cleaning_supplies",
      phrases: { en: ["cleaning products"], fr: ["produits d'entretien"] },
    },
    { id: "gardening", phrases: { en: ["gardening"], fr: ["jardinage"] } },
    {
      id: "moving",
      phrases: {
        en: ["moving company", "removal company", "removal van"],
        fr: ["déménageur", "camion de déménagement", "société de déménagement"],
      },
    },
    {
      id: "storage",
      merchants: ["shurgard", "annexx", "homebox"],
      phrases: {
        en: ["self storage", "storage unit"],
        fr: ["garde-meuble", "box de stockage"],
      },
    },
    {
      id: "down_payment",
      phrases: { en: ["down payment"], fr: ["apport", "acompte immobilier"] },
    },
    {
      id: "home_purchase",
      phrases: {
        en: ["house purchase", "flat purchase", "property purchase"],
        fr: [
          "achat immobilier",
          "acquisition immobilière",
          "achat de la maison",
          "achat appartement",
        ],
      },
    },
    {
      id: "security_deposit",
      phrases: {
        en: ["security deposit", "rental deposit"],
        fr: ["dépôt de garantie", "caution du bail"],
      },
    },
    {
      id: "property_tax",
      phrases: { en: ["property tax"], fr: ["taxe foncière"] },
    },
    {
      id: "waste",
      phrases: { en: ["waste collection"], fr: ["taxe déchets"] },
    },
  ],
  lodging: [
    {
      id: "vacation_rental",
      merchants: ["airbnb", "vrbo", "abritel"],
      phrases: { en: ["vacation rental"], fr: ["location de vacances"] },
    },
    {
      id: "hotel",
      merchants: ["ibis", "novotel", "mercure", "marriott", "hilton"],
      phrases: { en: ["hotel night"], fr: ["nuit d'hôtel"] },
    },
    { id: "camping", phrases: { en: ["campsite"], fr: ["camping"] } },
    {
      id: "hostel",
      phrases: { en: ["hostel"], fr: ["auberge de jeunesse"] },
    },
  ],
  subscriptions: [
    {
      id: "streaming",
      merchants: [
        "netflix",
        "spotify",
        "disney plus",
        "hbo max",
        "prime video",
        "deezer",
        "canal plus",
      ],
      phrases: { en: ["streaming"], fr: ["streaming"] },
    },
    {
      id: "cloud_storage",
      merchants: ["dropbox", "icloud", "google one"],
      phrases: { en: ["cloud storage"], fr: ["stockage cloud"] },
    },
    {
      id: "software",
      merchants: ["adobe", "microsoft 365", "jetbrains", "github"],
      phrases: { en: ["software licence"], fr: ["licence logicielle"] },
    },
  ],
  health: [
    { id: "pharmacy", phrases: { en: ["pharmacy"], fr: ["pharmacie"] } },
    { id: "dentist", phrases: { en: ["dentist"], fr: ["dentiste"] } },
    { id: "doctor", phrases: { en: ["doctor"], fr: ["médecin"] } },
    {
      id: "glasses_contacts",
      phrases: { en: ["glasses"], fr: ["lunettes"] },
    },
    {
      id: "physiotherapy",
      phrases: {
        en: ["physiotherapy", "physiotherapist"],
        fr: ["physiothérapie", "kinésithérapie", "kiné"],
      },
    },
    {
      id: "labs_tests",
      merchants: ["unilabs", "synlab", "viollier"],
      phrases: {
        en: ["blood test", "laboratory"],
        fr: ["prise de sang", "analyse médicale"],
      },
    },
    {
      id: "fitness",
      phrases: { en: ["gym membership"], fr: ["abonnement salle de sport"] },
    },
  ],
  entertainment: [
    { id: "cinema", phrases: { en: ["cinema"], fr: ["cinéma"] } },
    { id: "concerts", phrases: { en: ["concert"], fr: ["concert"] } },
  ],
  pets: [
    { id: "veterinary", phrases: { en: ["vet"], fr: ["vétérinaire"] } },
    { id: "grooming", phrases: { en: ["grooming"], fr: ["toilettage"] } },
    {
      id: "training",
      phrases: { en: ["dog training"], fr: ["dressage", "éducation canine"] },
    },
  ],
  kids_family: [
    {
      id: "childcare",
      phrases: {
        en: ["childcare", "nursery"],
        fr: ["garde d'enfants", "crèche"],
      },
    },
    {
      id: "babysitting",
      phrases: {
        en: ["babysitter", "babysitting"],
        fr: ["baby-sitter", "baby-sitting"],
      },
    },
    {
      id: "elder_care",
      phrases: {
        en: ["care home", "nursing home"],
        fr: ["maison de retraite", "ehpad"],
      },
    },
    {
      id: "child_support",
      phrases: { en: ["child support"], fr: ["pension alimentaire"] },
    },
    {
      id: "allowance",
      phrases: { en: ["pocket money"], fr: ["argent de poche"] },
    },
  ],
  finance_admin: [
    { id: "bank_fees", phrases: { en: ["bank fee"], fr: ["frais bancaires"] } },
    {
      id: "exchange_fees",
      phrases: { en: ["exchange fee"], fr: ["frais de change"] },
    },
    { id: "card_fees", phrases: { en: ["card fee"], fr: ["frais de carte"] } },
    {
      id: "taxes",
      phrases: {
        en: ["income tax", "tax return"],
        fr: ["impôt sur le revenu", "déclaration d'impôts"],
      },
    },
    {
      id: "accounting",
      phrases: {
        en: ["accountant", "bookkeeping"],
        fr: ["comptable", "expert-comptable"],
      },
    },
    {
      id: "legal",
      phrases: {
        en: ["lawyer", "solicitor", "notary"],
        fr: ["avocat", "notaire"],
      },
    },
    {
      id: "passport_visa",
      phrases: {
        en: ["passport renewal", "visa application"],
        fr: ["renouvellement passeport", "demande de visa"],
      },
    },
    {
      id: "fines",
      phrases: { en: ["speeding ticket"], fr: ["contravention"] },
    },
    {
      id: "interest",
      phrases: { en: ["interest charged"], fr: ["intérêts débiteurs"] },
    },
    {
      id: "loan_payment",
      phrases: { en: ["loan repayment"], fr: ["remboursement de prêt"] },
    },
  ],
  gifts_donations: [
    {
      id: "charity",
      merchants: [
        "unicef",
        "red cross",
        "croix rouge",
        "medecins sans frontieres",
        "msf",
        "wwf",
        "greenpeace",
        "amnesty international",
        "caritas",
        "terre des hommes",
        "handicap international",
        "restos du coeur",
      ],
      phrases: {
        en: ["charity", "charitable donation"],
        fr: ["œuvre caritative", "association caritative"],
      },
    },
    {
      id: "donations",
      merchants: ["gofundme", "helloasso", "leetchi"],
      phrases: {
        en: ["donation", "fundraiser"],
        fr: ["don", "collecte de fonds"],
      },
    },
    {
      id: "weddings",
      phrases: { en: ["wedding gift"], fr: ["cadeau de mariage"] },
    },
    {
      id: "birthdays",
      phrases: { en: ["birthday present"], fr: ["cadeau d'anniversaire"] },
    },
  ],
  personal_care: [
    {
      id: "hairdresser",
      phrases: {
        en: ["haircut", "hairdresser", "hair salon"],
        fr: ["coiffeur", "salon de coiffure", "coupe de cheveux"],
      },
    },
    { id: "barber", phrases: { en: ["barber"], fr: ["barbier"] } },
    {
      id: "beauty",
      phrases: {
        en: ["nail salon", "manicure", "beauty salon"],
        fr: ["manucure", "institut de beauté"],
      },
    },
    {
      id: "cosmetics",
      merchants: ["sephora", "marionnaud", "nocibe", "douglas parfumerie"],
      phrases: {
        en: ["cosmetics", "perfume", "make up"],
        fr: ["cosmétiques", "parfum", "maquillage"],
      },
    },
    {
      id: "skincare",
      phrases: { en: ["skincare", "facial"], fr: ["soin du visage"] },
    },
    {
      id: "toiletries",
      phrases: { en: ["toiletries"], fr: ["produits d'hygiène"] },
    },
    {
      id: "spa",
      phrases: { en: ["spa day", "hammam"], fr: ["spa", "hammam"] },
    },
    { id: "massage", phrases: { en: ["massage"], fr: ["massage"] } },
    {
      id: "laundry_dry_cleaning",
      phrases: {
        en: ["dry cleaning", "dry cleaner", "laundrette"],
        fr: ["pressing", "blanchisserie", "laverie"],
      },
    },
  ],
  education: [
    {
      id: "tuition",
      phrases: {
        en: ["tuition", "tuition fee", "university fee", "semester fee"],
        fr: ["frais de scolarité", "frais universitaires", "écolage"],
      },
    },
    {
      id: "school",
      phrases: {
        en: ["school fee", "school lunch", "school trip"],
        fr: ["frais scolaires", "cantine scolaire", "sortie scolaire"],
      },
    },
    {
      id: "courses",
      merchants: [
        "coursera",
        "udemy",
        "edx",
        "openclassrooms",
        "duolingo",
        "babbel",
      ],
      phrases: {
        en: ["language course", "evening class", "online course"],
        fr: ["cours de langue", "cours du soir", "cours en ligne"],
      },
    },
    {
      id: "training",
      phrases: {
        en: ["professional training", "training course", "certification"],
        fr: ["formation professionnelle", "formation continue"],
      },
    },
    {
      id: "tutoring",
      phrases: {
        en: ["private tutor", "tutoring"],
        fr: ["soutien scolaire", "cours particulier"],
      },
    },
    {
      id: "school_supplies",
      phrases: { en: ["school supplies"], fr: ["fournitures scolaires"] },
    },
    {
      id: "books_materials",
      phrases: {
        en: ["textbook", "school books"],
        fr: ["manuel scolaire", "livre scolaire"],
      },
    },
    {
      id: "exams",
      phrases: {
        en: ["exam fee", "exam registration"],
        fr: ["frais d'examen"],
      },
    },
  ],
  /**
   * Which policy, read out of the text. The premium is already settled by the
   * time these run, so all they answer is what it covers — and a premium that
   * does not say stays `insurance` with nothing under it, which is the whole
   * point of the second level being optional.
   */
  insurance: [
    {
      id: "home",
      phrases: {
        en: [
          "home insurance",
          "contents insurance",
          "building insurance",
          "tenant insurance",
        ],
        fr: ["assurance habitation", "assurance ménage", "assurance logement"],
      },
    },
    {
      id: "vehicle",
      phrases: {
        en: ["car insurance", "vehicle insurance", "motor insurance"],
        fr: ["assurance auto", "assurance automobile", "assurance véhicule"],
      },
    },
    {
      id: "health",
      merchants: [
        "groupe mutuel",
        "css assurance",
        "helsana",
        "swica",
        "sanitas",
        "visana",
        "concordia",
        "assura",
        "atupri",
        "sympany",
        "harmonie mutuelle",
      ],
      phrases: {
        en: ["health insurance"],
        fr: ["assurance maladie", "caisse maladie", "prime maladie"],
      },
    },
    { id: "life", phrases: { en: ["life insurance"], fr: ["assurance vie"] } },
    {
      id: "travel",
      phrases: { en: ["travel insurance"], fr: ["assurance voyage"] },
    },
    {
      id: "liability",
      phrases: { en: ["liability insurance"], fr: ["responsabilité civile"] },
    },
    {
      id: "legal_protection",
      phrases: {
        en: ["legal protection insurance", "legal expenses insurance"],
        fr: ["protection juridique"],
      },
    },
    {
      id: "disability",
      phrases: {
        en: ["disability insurance", "income protection"],
        fr: ["assurance invalidité"],
      },
    },
  ],
  shopping: [
    {
      id: "clothing",
      merchants: [
        "h&m",
        "zara",
        "uniqlo",
        "mango",
        "kiabi",
        "primark",
        "zalando",
        "asos",
      ],
      phrases: {
        en: ["clothing", "clothes"],
        fr: ["vêtements", "habillement"],
      },
    },
    {
      id: "electronics",
      merchants: [
        "mediamarkt",
        "fnac",
        "darty",
        "digitec",
        "galaxus",
        "interdiscount",
      ],
      phrases: { en: ["electronics"], fr: ["électronique"] },
    },
    {
      id: "sporting_goods",
      merchants: [
        "decathlon",
        "intersport",
        "ochsner sport",
        "sportxx",
        "athleticum",
      ],
      phrases: { en: ["sports equipment"], fr: ["matériel de sport"] },
    },
    {
      id: "toys",
      merchants: ["franz carl weber", "king jouet", "la grande recre"],
      phrases: { en: ["toys"], fr: ["jouets"] },
    },
    {
      id: "books",
      merchants: ["orell fussli", "payot librairie", "cultura"],
      phrases: { en: ["bookshop"], fr: ["librairie"] },
    },
    {
      id: "shoes",
      phrases: { en: ["shoes", "trainers"], fr: ["chaussures", "baskets"] },
    },
  ],
};
