import type { ExpenseCategory } from "./types";

/**
 * Global category seed rules.
 *
 * This file is *data*. Adding a merchant or a phrase should never require
 * touching the classifier, and the classifier never hard-codes a brand.
 *
 * Phrases are grouped by language for maintenance only — matching is
 * language-agnostic, because a transaction does not say which language it is
 * in. A French speaker's card can perfectly well produce `MONTHLY RENT`.
 *
 * The four strengths, weakest to strongest:
 *
 *  - `weakKeywords`     a word that leans one way (`grill`, `mobilité`)
 *  - `ambiguousMerchants` a real brand that sells across categories
 *  - `merchantFragments`  a word that names the trade (`pharmacie`, `vet`)
 *  - `merchants`          a brand that means one category
 *  - `strongPhrases`      the activity said outright (`billet de train`)
 *
 * `excludes` suppresses a category's *text* evidence when a disqualifying
 * word is present — it never overrides a learned mapping or a merchant.
 *
 * Two things to know before adding a word:
 *
 *  - **Write the singular; the plural comes free.** Text is matched on
 *    singularised tokens, so `glace` covers `glaces` and `meuble` covers
 *    `meubles`. Only a trailing `s` or `x` comes off (see `singularize`), so
 *    an irregular plural is still its own entry. Merchants are *not* folded
 *    this way — a brand is a name.
 *  - **A word in two categories is a tie, not a hint.** Two 0.9 phrases
 *    cancel each other out on the margin rule and the field is left for the
 *    user to fill. Repeating a word across categories is therefore a
 *    deliberate statement that it really is ambiguous, not a way to cover
 *    both.
 *
 * See `docs/categorization.md` for how to extend any of this.
 */

/** Keyed by BCP-47 primary language subtag. Add a language by adding a key. */
export type PhrasesByLanguage = Readonly<Record<string, readonly string[]>>;

export interface CategorySeed {
  readonly id: ExpenseCategory;
  readonly strongPhrases: PhrasesByLanguage;
  readonly weakKeywords?: PhrasesByLanguage;
  /** Brands, matched against the normalized merchant only. */
  readonly merchants?: readonly string[];
  /** Trade words, matched anywhere in the normalized merchant. */
  readonly merchantFragments?: readonly string[];
  /** Brands that genuinely span categories: a hint, never a decision. */
  readonly ambiguousMerchants?: readonly string[];
  /** Words whose presence disqualifies this category's text evidence. */
  readonly excludes?: readonly string[];
}

export const CATEGORY_SEEDS: readonly CategorySeed[] = [
  {
    id: "groceries",
    strongPhrases: {
      en: [
        "groceries",
        "grocery store",
        "grocery shopping",
        "supermarket",
        "food shopping",
        "weekly groceries",
        "weekly shop",
        "food market",
        "convenience store",
        "organic grocery",
        "farmers market",
        "butcher",
        "butcher shop",
        "greengrocer",
        "fishmonger",
        "cheese shop",
        "food for the week",
        "household food",
        "bread",
        "milk",
        "eggs",
        "cheese",
        "butter",
        "yoghurt",
        "yogurt",
        "fruit",
        "fruits",
        "vegetables",
        "veggies",
        "pasta",
        "rice",
        "flour",
        "sugar",
        "cereal",
        "olive oil",
        "meat",
        "fish",
        "bottled water",
        "food shop",
        "food run",
        "snacks for the week",
        "perrier",
        "evian",
        "vittel",
        "san pellegrino",
        "henniez",
        "rivella",
        "tropicana",
        "pringles",
        "doritos",
        "haribo",
        "kinder",
        "nutella",
        "oreo",
        "twix",
        "snickers",
        "toblerone",
        "lindt",
        "milka",
        "ferrero rocher",
        "barilla",
        "nesquik",
        "danone",
        "activia",
        "philadelphia",
        "babybel",
        "heinz",
        "kelloggs",
        "nescafé",
        "nespresso",
        "pepsi",
        "fuze tea",
        "fuzetea",
        "ice tea",
        "iced tea",
        "nestea",
        "sprite",
        "fanta",
        "orangina",
        "schweppes",
        "red bull",
        "redbull",
        "monster",
        "capri sun",
        "gatorade",
        "powerade",
        "heineken",
        "kronenbourg",
        "desperados",
        "corona",
        "guinness",
        "magnum",
        "cornetto",
        "feldschlösschen",
        "cardinal",
        "coca",
        "coca cola",
        "cola",
        "limonade",
      ],
      fr: [
        "courses",
        "courses alimentaires",
        "courses de la semaine",
        "supermarché",
        "hypermarché",
        "supérette",
        "épicerie",
        "épicerie bio",
        "marché alimentaire",
        "magasin alimentaire",
        "achat alimentaire",
        "alimentation",
        "boucherie",
        "poissonnerie",
        "fromagerie",
        "primeur",
        "au marché",
        "pain",
        "lait",
        "oeufs",
        "beurre",
        "fromage",
        "yaourt",
        "yaourts",
        "fruits",
        "légumes",
        "pâtes",
        "riz",
        "huile",
        "huile d'olive",
        "céréales",
        "viande",
        "poisson",
        "eau",
        "bouteille d'eau",
        "ravitaillement",
        "de quoi manger",
        "boulangerie",
        "pâtisserie",
        "viennoiseries",
      ],
    },
    weakKeywords: {
      en: [
        "market",
        "food",
        "fresh",
        "organic",
        "bio",
        "deli",
        "groceries",
        "shop",
      ],
      fr: [
        "farine",
        "sucre",
        "marché",
        "alimentation",
        "alimentaire",
        "frais",
        "bio",
        "vrac",
        "provisions",
      ],
    },
    merchants: [
      "migros",
      "migros m",
      "migros mm",
      "migros mmm",
      "migros online",
      "migros partner",
      "leshop",
      "coop supermarket",
      "coop city food",
      "coop alimentaire",
      "denner",
      "denner express",
      "aldi",
      "aldi suisse",
      "aldi france",
      "aldi nord",
      "aldi sud",
      "lidl",
      "carrefour",
      "carrefour market",
      "carrefour city",
      "carrefour contact",
      "carrefour express",
      "monoprix",
      "monop",
      "franprix",
      "e leclerc",
      "leclerc",
      "leclerc drive",
      "intermarché",
      "intermarche",
      "auchan",
      "casino",
      "spar",
      "volg",
      "manor food",
      "globus delicatessa",
      "picard",
      "super u",
      "hyper u",
      "u express",
      "grand frais",
      "biocoop",
      "naturalia",
      "satoriz",
      "la vie claire",
      "prodega",
      "aligro",
      "metro cash and carry",
      "farmy",
      "hellofresh",
      "gorillas",
      "flink",
      "getir",
      "picnic",
      "albert heijn",
      "delhaize",
      "colruyt",
      "rewe",
      "edeka",
      "kaufland",
      "netto",
      "penny markt",
      "mercadona",
      "esselunga",
      "conad",
      "tesco",
      "sainsbury",
      "waitrose",
    ],
    merchantFragments: [
      "supermarche",
      "supermarkt",
      "epicerie",
      "boucherie",
      "poissonnerie",
      "fromagerie",
      "superette",
      "grocery",
      "supermarket",
    ],
    excludes: [
      // A bill for something is not a trip to the shop, whatever it is for.
      "facture",
      "bill",
      "invoice",
      // Bread the group ate on the way is not bread for the flat.
      "pain au chocolat",
      "fish and chips",
      // English keeps a word for bread that French uses for suffering.
      "back pain",
      "neck pain",
      "chest pain",
      "joint pain",
      "period pain",
      "pain relief",
      "pain killer",
      "painkiller",
      "in pain",
      // And perfume is sold by the water.
      "eau de parfum",
      "eau de toilette",
      "eau de cologne",
    ],
    ambiguousMerchants: [
      // Forecourt and kiosk formats: groceries as often as fuel or a sandwich.
      "coop pronto",
      "migrolino",
      "avec",
      "shell select",
      "bp shop",
      "k kiosk",
      "aperto",
      "relay",
      // Bare "Coop" fronts a supermarket, a pharmacy and a filling station.
      "coop",
    ],
  },
  {
    id: "restaurants",
    strongPhrases: {
      en: [
        "restaurant",
        "cafe",
        "coffee shop",
        "bar",
        "pub",
        "bistro",
        "brasserie",
        "takeaway",
        "takeout",
        "food delivery",
        "lunch",
        "dinner",
        "breakfast",
        "brunch",
        "pizza",
        "burger",
        "sushi",
        "kebab",
        "tapas",
        "ramen",
        "poke bowl",
        "food truck",
        "street food",
        "bakery cafe",
        "fast food",
        "ice cream",
        "gelato",
        "frozen yogurt",
        "wine bar",
        "cocktail bar",
        "happy hour",
        "steakhouse",
        "meal out",
        "eating out",
        "drinks out",
        "coffee",
        "iced coffee",
        "hot chocolate",
        "milkshake",
        "smoothie",
        "waffle",
        "crepe",
        "pancakes",
        "donut",
        "doughnut",
        "churros",
        "cotton candy",
        "hot dog",
        "falafel",
        "shawarma",
        "noodles",
        "dim sum",
        "fish and chips",
        "chicken wings",
        "nachos",
        "beer",
        "wine",
        "cocktail",
        "drinks",
        "round of drinks",
        "take away",
        "snack bar",
        "food stand",
        "fries",
        "aperol",
        "aperol spritz",
        "spritz",
        "mojito",
        "ricard",
        "crisps and dips",
        "bakery",
        "pastry",
      ],
      fr: [
        "restaurant",
        "café",
        "bar",
        "bistrot",
        "bistro",
        "brasserie",
        "repas",
        "déjeuner",
        "dîner",
        "souper",
        "petit déjeuner",
        "brunch",
        "livraison de repas",
        "repas à emporter",
        "à emporter",
        "pizzeria",
        "sushi",
        "kebab",
        "crêperie",
        "fast-food",
        // In an expense, a "glace" is eaten. The ice and the mirror the word
        // also means are not things a group splits the cost of.
        "glace",
        "glaces",
        "glace italienne",
        "crème glacée",
        "cornet de glace",
        "apéro",
        "apéritif",
        "boire un verre",
        "resto",
        "au resto",
        "traiteur",
        "buvette",
        "restau",
        "bière",
        "vin",
        "verre de vin",
        "cocktail",
        "gaufre",
        "crêpe",
        "crêpes au sucre",
        "beignet",
        "churros",
        "barbe à papa",
        "chocolat chaud",
        "milkshake",
        "smoothie",
        "frites",
        "hamburger",
        "sandwich",
        "panini",
        "tacos",
        "falafel",
        "nouilles",
        "ramen",
        "hot dog",
        "croissant",
        "pain au chocolat",
        "viennoiserie",
        "boulangerie",
        "pâtisserie",
        "goûter",
        "casse-croûte",
        "terrasse",
        "en terrasse",
        "sur le pouce",
        "boisson",
        "boissons",
        "soda",
        "sirop",
      ],
    },
    weakKeywords: {
      en: [
        "kitchen",
        "grill",
        "pizza",
        "sushi",
        "burger",
        "bakery",
        "coffee",
        "espresso",
        "tea room",
        "beer",
        "beers",
        "wine",
        "cocktail",
        "cocktails",
        "tavern",
        "snack",
        "snacks",
        "cafeteria",
        "canteen",
        "brewery",
        "taco",
        "tacos",
        "barbecue",
        "bbq",
      ],
      fr: [
        "cuisine",
        "grill",
        "boulangerie",
        "pâtisserie",
        "café",
        "salon de thé",
        "bière",
        "bières",
        "vin",
        "vins",
        "cocktail",
        "cocktails",
        "taverne",
        "snack",
        "cantine",
        "manger",
        "sandwich",
        "sandwichs",
        "viennoiserie",
        "goûter",
      ],
    },
    merchants: [
      "mcdonald",
      "burger king",
      "kfc",
      "subway",
      "starbucks",
      "costa coffee",
      "tim hortons",
      "dunkin",
      "five guys",
      "domino",
      "dominos",
      "pizza hut",
      "taco bell",
      "chipotle",
      "nando",
      "pret a manger",
      "vapiano",
      "l osteria",
      "holy cow",
      "tibits",
      "hiltl",
      "manora",
      "autogrill",
      "brezelkonig",
      "brezelkönig",
      "coop restaurant",
      "migros restaurant",
      "uber eats",
      "ubereats",
      "deliveroo",
      "just eat",
      "justeat",
      "eat ch",
      "smood",
      "wolt",
      "glovo",
      "lieferando",
      "too good to go",
      "ben and jerry",
      "ben and jerrys",
      "ben and jerry s",
      "haagen dazs",
      "häagen dazs",
      "amorino",
      "movenpick glace",
      "mövenpick glace",
      "mcdo",
      "mcdonalds",
      "pret a manger",
      "dominos pizza",
      "wagamama",
      "sprüngli",
      "sprungli",
      "laduree",
      "ladurée",
      "movenpick",
      "mövenpick",
      "luigia",
      "gelateria",
      "creperie",
      "crêperie",
      "glacier",
    ],
    merchantFragments: [
      "restaurant",
      "ristorante",
      "trattoria",
      "osteria",
      "pizzeria",
      "brasserie",
      "bistrot",
      "taverne",
      "gelateria",
      "creperie",
      "crêperie",
      "kebab",
      "cafeteria",
    ],
    excludes: ["supermarket", "grocery", "supermarché"],
  },
  {
    id: "transport",
    strongPhrases: {
      en: [
        "public transport",
        "bus ticket",
        "train ticket",
        "metro ticket",
        "tram ticket",
        "travel pass",
        "monthly travel pass",
        "half fare",
        "taxi",
        "ride sharing",
        "rideshare",
        "car sharing",
        "parking",
        "car park",
        "parking fine",
        "toll",
        "motorway toll",
        "motorway vignette",
        "fuel",
        "petrol",
        "gasoline",
        "diesel",
        "charging station",
        "ev charging",
        "bike rental",
        "bike repair",
        "scooter rental",
        "car rental",
        "car wash",
        "car service",
        "driving lesson",
        "roadside assistance",
        "bus",
        "tram",
        "metro",
        "underground",
        "ferry",
        "bike",
        "scooter",
        "vignette",
        "petrol station",
        "fuel up",
      ],
      fr: [
        "transports publics",
        "billet de train",
        "billet de bus",
        "billet de métro",
        "billet de tram",
        "abonnement général",
        "demi-tarif",
        "carte journalière",
        "taxi",
        "covoiturage",
        "autopartage",
        "parking",
        "stationnement",
        "amende de stationnement",
        "péage",
        "autoroute",
        "vignette autoroute",
        "essence",
        "carburant",
        "diesel",
        "borne de recharge",
        "recharge électrique",
        "location de vélo",
        "réparation vélo",
        "location de trottinette",
        "location de voiture",
        "lavage voiture",
        "révision voiture",
        "bus",
        "métro",
        "tram",
        "tramway",
        "ferry",
        "bateau",
        "vélo",
        "trottinette",
        "gasoil",
        "gazole",
        "vignette",
        "ticket de bus",
        "ticket de métro",
        "carte de transport",
        "plein d'essence",
        "faire le plein",
        "contrôle technique",
        "leçon de conduite",
        "auto-école",
        "dépannage",
      ],
    },
    weakKeywords: {
      en: [
        "station",
        "mobility",
        "transport",
        "ticket",
        "transit",
        "garage",
        "bus",
        "train",
        "tram",
        "metro",
        "scooter",
        "tyres",
        "tires",
      ],
      fr: [
        "gare",
        "mobilité",
        "transport",
        "billet",
        "station",
        "garage",
        "bus",
        "train",
        "tram",
        "métro",
        "vélo",
        "trottinette",
        "pneus",
      ],
    },
    merchants: [
      "sbb",
      "cff",
      "ffs",
      "sbb cff ffs",
      "bls",
      "tpg",
      "tl lausanne",
      "transports publics genevois",
      "tpf",
      "vmcv",
      "cgn",
      "zvv",
      "rhb",
      "bernmobil",
      "vbz",
      "bvb",
      "carpostal",
      "postauto",
      "sncf",
      "sncf connect",
      "ouigo",
      "trainline",
      "omio",
      "eurostar",
      "thalys",
      "trenitalia",
      "italo treno",
      "deutsche bahn",
      "ratp",
      "tcl",
      "transdev",
      "flixbus",
      "blablacar",
      "alsa",
      "uber",
      "bolt",
      "free now",
      "freenow",
      "lime",
      "dott",
      "tier",
      "voi scooters",
      "swapfiets",
      "publibike",
      "mobility carsharing",
      "getaround",
      "easypark",
      "parkingpay",
      "indigo parking",
      "apcoa",
      "q park",
      "q-park",
      "vinci autoroutes",
      "sanef",
      "aprr",
      "europcar",
      "sixt",
      "hertz",
      "avis",
      "budget rent a car",
      "enterprise rent a car",
      "ionity",
      "chargepoint",
      "evpass",
      "shell recharge",
      "tesla supercharger",
    ],
    /**
     * Filling stations. Deliberately *not* plain merchants: half of what is
     * bought at one is a sandwich. `contextualOverrides` promotes them to a
     * decision as soon as the text mentions fuel.
     */
    ambiguousMerchants: [
      "shell",
      "bp",
      "esso",
      "avia",
      "tamoil",
      "migrol",
      "eni",
      "agrola",
      "socar",
      "tcs",
    ],
  },
  {
    id: "housing",
    strongPhrases: {
      en: [
        "rent",
        "monthly rent",
        "apartment rent",
        "house rent",
        "rental payment",
        "landlord",
        "property management",
        "mortgage",
        "mortgage payment",
        "condominium fee",
        "hoa fee",
        "building maintenance",
        "tenant charge",
        "service charges",
        "rental deposit",
        "security deposit",
        "home insurance",
        "property tax",
        "council tax",
      ],
      fr: [
        "loyer",
        "loyer mensuel",
        "paiement du loyer",
        "régie immobilière",
        "régie",
        "bailleur",
        "bail",
        "hypothèque",
        "prêt hypothécaire",
        "charges de copropriété",
        "charges locatives",
        "entretien immeuble",
        "garantie de loyer",
        "caution loyer",
        "état des lieux",
        "assurance ménage",
        "assurance habitation",
        "taxe d'habitation",
        "taxe foncière",
      ],
    },
    weakKeywords: {
      en: ["apartment", "housing", "property", "building", "flat", "tenancy"],
      fr: [
        "appartement",
        "logement",
        "immeuble",
        "immobilier",
        "colocation",
        "coloc",
      ],
    },
    merchants: [
      "livit",
      "wincasa",
      "privera",
      "bernard nicod",
      "pilet renaud",
      "foncia",
      "nexity",
    ],
    merchantFragments: [
      "immobilier",
      "immobilière",
      "property management",
      "real estate management",
      "régie",
      "gérance",
      "gerance",
    ],
  },
  {
    id: "utilities",
    strongPhrases: {
      en: [
        "electricity bill",
        "electricity",
        "power bill",
        "gas bill",
        "natural gas",
        "water bill",
        "internet bill",
        "broadband",
        "mobile phone",
        "phone bill",
        "telecom",
        "heating",
        "district heating",
        "heating oil",
        "waste collection",
        "utilities",
        "tv licence",
        "meter reading",
        "mobile plan",
        "phone plan",
        "internet subscription",
        "water charges",
      ],
      fr: [
        "facture électricité",
        "électricité",
        "facture gaz",
        "gaz naturel",
        "facture eau",
        "facture d'eau",
        "internet",
        "fibre",
        "téléphonie",
        "téléphone",
        "abonnement mobile",
        "chauffage",
        "chauffage urbain",
        "mazout",
        "collecte des déchets",
        "taxe déchets",
        "services industriels",
        "redevance radio",
        "redevance tv",
        "relevé compteur",
        "gaz",
        "facture de gaz",
        "facture d'électricité",
        "facture internet",
        "forfait mobile",
        "forfait téléphonique",
        "abonnement internet",
        "box internet",
        "eau chaude",
      ],
    },
    weakKeywords: {
      en: ["energy", "telecom", "water", "broadband", "fiber", "fibre", "bill"],
      fr: ["énergie", "télécom", "eau", "fibre", "facture", "compteur"],
    },
    merchants: [
      "swisscom",
      "sunrise",
      "salt mobile",
      "wingo",
      "yallo",
      "lyca mobile",
      "lebara",
      "m budget mobile",
      "digitec connect",
      "init7",
      "quickline",
      "netplus",
      "vtx",
      "upc",
      "serafe",
      "billag",
      "sig geneve",
      "services industriels geneve",
      "viteos",
      "romande energie",
      "groupe e",
      "ewz",
      "iwb",
      "primeo energie",
      "bkw",
      "ckw",
      "axpo",
      "orange",
      "orange france",
      "sfr",
      "bouygues telecom",
      "free mobile",
      "free telecom",
      "edf",
      "engie",
      "veolia",
      "suez",
    ],
  },
  {
    id: "shopping",
    strongPhrases: {
      en: [
        "clothing",
        "clothes",
        "electronics",
        "online shopping",
        "department store",
        "shoes",
        "trainers",
        "accessories",
        "jewellery",
        "watch",
        "consumer electronics",
        "phone case",
        "headphones",
        "laptop",
        "bookshop",
        "stationery",
        "cosmetics",
        "perfume",
        "make up",
        "hairdresser",
        "barber",
        "nail salon",
        "sports equipment",
      ],
      fr: [
        "vêtements",
        "habillement",
        "électronique",
        "achats en ligne",
        "grand magasin",
        "chaussures",
        "baskets",
        "accessoires",
        "bijoux",
        "montre",
        "casque audio",
        "ordinateur portable",
        "librairie",
        "papeterie",
        "cosmétiques",
        "parfum",
        "maquillage",
        "coiffeur",
        "salon de coiffure",
        "barbier",
        "manucure",
        "matériel de sport",
      ],
    },
    weakKeywords: {
      en: ["clothes", "shoes", "outfit", "jacket", "shirt", "boutique"],
      fr: [
        "vêtement",
        "chaussure",
        "tenue",
        "veste",
        "pull",
        "boutique",
        "coiffure",
      ],
    },
    merchants: [
      "galaxus",
      "digitec",
      "brack",
      "interdiscount",
      "melectronics",
      "microspot",
      "steg electronics",
      "back market",
      "backmarket",
      "h&m",
      "hm",
      "zara",
      "uniqlo",
      "mango",
      "c&a",
      "kiabi",
      "primark",
      "tally weijl",
      "chicoree",
      "chicorée",
      "zalando",
      "asos",
      "shein",
      "vinted",
      "veepee",
      "about you",
      "dosenbach",
      "ochsner sport",
      "sportxx",
      "athleticum",
      "decathlon",
      "intersport",
      "mediamarkt",
      "media markt",
      "fnac",
      "darty",
      "cdiscount",
      "temu",
      "aliexpress",
      "apple store",
      "samsung store",
      "sephora",
      "marionnaud",
      "douglas parfumerie",
      "nocibe",
      "yves rocher",
      "the body shop",
      "globus",
      "loeb",
      "galeries lafayette",
      "printemps",
      "orell fussli",
      "payot librairie",
      "cultura",
    ],
    /**
     * Platforms, not shops. Amazon sells groceries, Apple sells subscriptions,
     * Manor runs a supermarket; `contextualOverrides` resolves the common
     * cases and everything else stays a suggestion.
     */
    ambiguousMerchants: ["amazon", "apple", "google", "manor"],
  },
  {
    id: "health",
    strongPhrases: {
      en: [
        "doctor",
        "physician",
        "medical",
        "hospital",
        "clinic",
        "pharmacy",
        "medication",
        "medicine",
        "prescription",
        "dentist",
        "dental",
        "orthodontist",
        "optician",
        "glasses",
        "contact lenses",
        "physiotherapy",
        "therapist",
        "therapy session",
        "laboratory",
        "medical test",
        "blood test",
        "vaccination",
        "consultation",
        "emergency room",
        "health insurance",
        "osteopath",
        "chiropractor",
        "massage",
        "hearing aid",
      ],
      fr: [
        "médecin",
        "médical",
        "hôpital",
        "clinique",
        "pharmacie",
        "médicament",
        "ordonnance",
        "dentiste",
        "dentaire",
        "orthodontiste",
        "opticien",
        "lunettes",
        "lentilles",
        "physiothérapie",
        "physiothérapeute",
        "thérapeute",
        "laboratoire",
        "analyse médicale",
        "prise de sang",
        "vaccination",
        "consultation",
        "urgences",
        "assurance maladie",
        "caisse maladie",
        "prime maladie",
        "ostéopathe",
        "chiropracteur",
        "massage",
        "psychologue",
        "appareil auditif",
      ],
    },
    merchants: [
      "amavita",
      "sun store",
      "sunstore",
      "coop vitality",
      "benu",
      "toppharm",
      "pharmacieplus",
      "galenica",
      "medbase",
      "hirslanden",
      "chuv",
      "hug",
      "unilabs",
      "synlab",
      "viollier",
      "groupe mutuel",
      "css assurance",
      "helsana",
      "swica",
      "sanitas",
      "visana",
      "concordia",
      "assura",
      "atupri",
      "sympany",
      "harmonie mutuelle",
    ],
    merchantFragments: [
      "pharmacie",
      "pharmacy",
      "apotheke",
      "pharma",
      "clinique",
      "clinic",
      "dental",
      "dentaire",
      "dentist",
      "dentiste",
      "medical",
      "médical",
      "optique",
      "optical",
      "optik",
      "laboratoire",
      "laboratory",
      "physio",
      "physiotherapie",
      "osteopathe",
      "hopital",
      "hôpital",
      "hospital",
      "permanence",
    ],
  },
  {
    id: "entertainment",
    strongPhrases: {
      en: [
        "cinema",
        "movie theatre",
        "movie theater",
        "theatre",
        "theater",
        "concert",
        "festival",
        "opera",
        "comedy show",
        "nightclub",
        "karaoke",
        "gaming",
        "video game",
        "game purchase",
        "event ticket",
        "gig ticket",
      ],
      fr: [
        "cinéma",
        "théâtre",
        "concert",
        "festival",
        "opéra",
        "spectacle",
        "discothèque",
        "boîte de nuit",
        "karaoké",
        "jeu vidéo",
        "jeux vidéo",
        "billet spectacle",
        "billet concert",
      ],
    },
    merchants: [
      "pathe",
      "pathé",
      "arena cinemas",
      "blue cinema",
      "cinepel",
      "ugc",
      "gaumont",
      "kinepolis",
      "ticketmaster",
      "ticketcorner",
      "starticket",
      "petzi",
      "eventim",
      "see tickets",
      "fnac spectacles",
      "steam",
      "playstation",
      "playstation network",
      "xbox",
      "nintendo",
      "epic games",
      "riot games",
      "blizzard",
      "humble bundle",
      "gog com",
    ],
    // A console store charging every month is a subscription, not an outing.
    excludes: ["monthly", "subscription", "abonnement"],
  },
  {
    id: "travel",
    /**
     * Getting there, and the trip as a purchase. Where people *slept* is
     * `lodging` — on any real holiday the accommodation is most of the total,
     * and leaving it here made a trip's chart a single bar.
     */
    strongPhrases: {
      en: [
        "airline",
        "plane ticket",
        "flight",
        "airfare",
        "travel booking",
        "travel agency",
        "package holiday",
        "airport transfer",
        "travel insurance",
        "excess baggage",
        "seat selection",
        "visa fee",
        "passport",
        "duty free",
      ],
      fr: [
        "compagnie aérienne",
        "billet d'avion",
        "vol",
        "réservation voyage",
        "agence de voyage",
        "séjour organisé",
        "navette aéroport",
        "assurance voyage",
        "bagage supplémentaire",
        "choix du siège",
        "frais de visa",
        "passeport",
        "duty free",
      ],
    },
    weakKeywords: {
      en: ["travel", "holiday", "vacation", "flight", "airport", "trip"],
      fr: ["voyage", "vacances", "vol", "aéroport", "séjour"],
    },
    merchants: [
      "easyjet",
      "swiss international",
      "swiss airlines",
      "edelweiss air",
      "ryanair",
      "air france",
      "klm",
      "lufthansa",
      "eurowings",
      "austrian airlines",
      "brussels airlines",
      "british airways",
      "iberia",
      "vueling",
      "transavia",
      "wizz air",
      "norwegian air",
      "tap portugal",
      "turkish airlines",
      "aegean airlines",
      "emirates",
      "qatar airways",
      "etihad",
      "singapore airlines",
      "cathay pacific",
      "air canada",
      "united airlines",
      "delta air lines",
      "american airlines",
      "expedia",
      "opodo",
      "edreams",
      "lastminute",
      "kayak",
      "skyscanner",
      "kiwi com",
      "kuoni",
      "hotelplan",
      "tui",
      "club med",
      "secret escapes",
    ],
  },
  {
    id: "lodging",
    /**
     * Where the trip slept. Split out of `travel` so a week's rental stops
     * swallowing the getting-there, the eating and the doing.
     */
    strongPhrases: {
      en: [
        "hotel",
        "hotel night",
        "hostel",
        "accommodation",
        "vacation rental",
        "holiday rental",
        "holiday apartment",
        "guest house",
        "bed and breakfast",
        "room booking",
        "campsite",
        "camping pitch",
        "resort stay",
        "mountain hut",
        "check in",
      ],
      fr: [
        "hôtel",
        "nuit d'hôtel",
        "nuitée",
        "nuitées",
        "auberge",
        "auberge de jeunesse",
        "hébergement",
        "location de vacances",
        "logement de vacances",
        "chambre d'hôtes",
        "gîte",
        "chalet",
        "camping",
        "emplacement camping",
        "réservation hôtel",
        "refuge",
        "cabane",
        "location appartement",
        "appartement de vacances",
        "location saisonnière",
        "nuit d'hôtel",
        "nuits d'hôtel",
        "hôtel",
        "motel",
        "pension",
      ],
    },
    weakKeywords: {
      en: ["hotel", "hostel", "room", "rooms", "nights", "stay", "bnb"],
      fr: ["chambre", "nuit", "nuits", "gîte", "refuge", "auberge", "logement"],
    },
    merchants: [
      "airbnb",
      "booking.com",
      "booking",
      "hotels.com",
      "hostelworld",
      "agoda",
      "trip.com",
      "vrbo",
      "abritel",
      "homeaway",
      "interhome",
      "e domizil",
      "swiss youth hostels",
      "accor",
      "ibis",
      "novotel",
      "mercure",
      "sofitel",
      "pullman",
      "marriott",
      "hilton",
      "hyatt",
      "radisson",
      "nh hotels",
      "premier inn",
      "travelodge",
      "campanile",
      "kyriad",
      "motel one",
      "citizenm",
      "25hours",
      "reka",
      "huttopia",
      "yelloh village",
      "center parcs",
      "landal",
      "pierre et vacances",
      "belambra",
      "odalys",
    ],
    merchantFragments: [
      "hotel",
      "hôtel",
      "hostel",
      "auberge",
      "camping",
      "motel",
      "guesthouse",
      "gasthof",
      "albergo",
      "pensione",
    ],
  },
  {
    id: "activities",
    /**
     * Tickets, tours and entries — the planned doing. Split out of
     * `entertainment`, which keeps the shows: a guided walk and a games
     * console were never the same line on a chart.
     */
    strongPhrases: {
      en: [
        "museum",
        "museum entry",
        "exhibition",
        "guided tour",
        "city tour",
        "sightseeing",
        "excursion",
        "day trip",
        "boat trip",
        "zoo",
        "aquarium",
        "theme park",
        "amusement park",
        "water park",
        "escape room",
        "escape game",
        "bowling",
        "mini golf",
        "ice skating",
        "diving",
        "kayaking",
        "canoeing",
        "paddleboarding",
        "climbing gym",
        "rafting",
        "ski lesson",
        "ski rental",
        "guided tour",
        "ski pass",
        "lift pass",
        "cable car",
        "climbing gym",
        "swimming pool",
        "wine tasting",
        "cooking class",
        "yoga class",
        "entrance fee",
        "entry ticket",
        "ski rental",
        "equipment rental",
      ],
      fr: [
        "musée",
        "entrée musée",
        "exposition",
        "visite guidée",
        "excursion",
        "randonnée",
        "parc d'attractions",
        "parc aquatique",
        "zoo",
        "aquarium",
        "escape game",
        "bowling",
        "mini golf",
        "patinoire",
        "forfait de ski",
        "forfait ski",
        "remontées mécaniques",
        "téléphérique",
        "salle d'escalade",
        "piscine",
        "dégustation",
        "cours de cuisine",
        "cours de yoga",
        "billet d'entrée",
        "droit d'entrée",
        "plongée",
        "kayak",
        "canoë",
        "paddle",
        "accrobranche",
        "via ferrata",
        "escalade",
        "parapente",
        "rafting",
        "snorkeling",
        "cours de ski",
        "location de skis",
        "entrée piscine",
        "match",
        "billet de match",
        "accrobranche",
        "karting",
        "laser game",
        "paintball",
        "location de skis",
        "location de matériel",
      ],
    },
    weakKeywords: {
      en: ["tour", "entry", "trail", "climbing", "hike", "fitness", "lesson"],
      fr: [
        "visite",
        "entrée",
        // "Sortie au restaurant" is Splitwise's own French for dining out, so
        // an outing is a hint here and never the answer.
        "sortie",
        "rando",
        "escalade",
        "ski",
        "parc",
        "atelier",
        "fitness",
        "cours",
      ],
    },
    merchants: [
      "europapark",
      "europa park",
      "disneyland",
      "parc asterix",
      "walibi",
      "aquaparc",
      "alpamare",
      "connyland",
      "swiss vapeur parc",
      "papiliorama",
      "verkehrshaus",
      "musee olympique",
      "chaplin s world",
      "jungfraujoch",
      "glacier 3000",
      "titlis",
      "gornergrat",
      "rochers de naye",
      "magic pass",
      "getyourguide",
      "viator",
      "tiqets",
      "klook",
      "civitatis",
    ],
    excludes: [
      // An outing bought for somebody is a present, and the word for it is
      // right there in the description. Without this, adding a sport to the
      // vocabulary silently un-decided every gift that named one.
      "cadeau",
      "cadeaux",
      "gift",
      "present for",
      "carte cadeau",
      "bon cadeau",
    ],
    merchantFragments: [
      "musee",
      "musée",
      "museum",
      "zoo",
      "aquarium",
      "patinoire",
      "bowling",
      "karting",
      "escalade",
      "fitness",
      "piscine",
    ],
  },
  {
    id: "household",
    /**
     * The upkeep of where people live: supplies, furniture, repairs. It used
     * to scatter between `shopping` (a thing was bought) and `housing` (the
     * flat was involved), which is why neither total meant anything.
     */
    strongPhrases: {
      en: [
        "household supplies",
        "cleaning products",
        "cleaning supplies",
        "laundry detergent",
        "toilet paper",
        "kitchen supplies",
        "kitchenware",
        "furniture",
        "home goods",
        "home decor",
        "hardware store",
        "diy store",
        "light bulbs",
        "garden centre",
        "gardening",
        "home repair",
        "appliance",
        "appliance repair",
        "plumber",
        "electrician",
        "handyman",
        "cleaning service",
        "moving boxes",
        "storage unit",
        "bed linen",
        "crockery",
        "sponges",
        "bin bags",
        "rubbish bags",
        "batteries",
        "curtains",
        "drill",
        "vacuum cleaner",
        "broom",
        "towels",
        "coat hangers",
      ],
      fr: [
        "produits ménagers",
        "produits d'entretien",
        "produits de nettoyage",
        "lessive",
        "papier toilette",
        "papier ménage",
        "vaisselle",
        "ustensiles de cuisine",
        "meubles",
        "mobilier",
        "décoration",
        "électroménager",
        "bricolage",
        "outils",
        "quincaillerie",
        "ampoules",
        "jardinage",
        "jardinerie",
        "éponges",
        "sacs poubelle",
        "sac poubelle",
        "piles",
        "rideaux",
        "perceuse",
        "visserie",
        "serviettes",
        "torchons",
        "cintres",
        "aspirateur",
        "balai",
        "produits ménage",
        "réparation maison",
        "plombier",
        "électricien",
        "serrurier",
        "femme de ménage",
        "service de nettoyage",
        "déménagement",
        "garde-meuble",
        "literie",
        "linge de maison",
      ],
    },
    weakKeywords: {
      en: [
        "cleaning",
        "detergent",
        "furniture",
        "garden",
        "tools",
        "repair",
        "diy",
        "hardware",
      ],
      fr: [
        "ménage",
        "entretien",
        "meuble",
        "meubles",
        "jardin",
        "outils",
        "réparation",
        "déco",
      ],
    },
    merchants: [
      "ikea",
      "conforama",
      "maisons du monde",
      "jumbo",
      "hornbach",
      "obi",
      "bauhaus",
      "brico depot",
      "bricorama",
      "leroy merlin",
      "castorama",
      "coop bau hobby",
      "coop bau und hobby",
      "do it garden",
      "migros do it",
      "landi",
      "jysk",
      "kave home",
      "westwing",
      "micasa",
      "interio",
      "pfister",
      "livique",
      "lipo",
      "ottos",
      "casa",
      "zara home",
      "flying tiger",
      "sostrene grene",
      "gifi",
      "centrakor",
      "botanic",
      "truffaut",
      "jardiland",
      "gamm vert",
      "schilliger",
    ],
    merchantFragments: [
      "quincaillerie",
      "droguerie",
      "jardinerie",
      "bricolage",
      "brico",
      "ameublement",
      "nettoyage",
      "plomberie",
    ],
    // Sells food, toys and cleaning products in the same basket.
    ambiguousMerchants: ["action"],
  },
  {
    id: "subscriptions",
    strongPhrases: {
      en: [
        "subscription",
        "monthly subscription",
        "annual subscription",
        "membership",
        "recurring subscription",
        "premium plan",
        "monthly plan",
        "yearly plan",
        "auto renewal",
        "family plan",
      ],
      fr: [
        "abonnement",
        "abonnement mensuel",
        "abonnement annuel",
        "adhésion",
        "cotisation",
        "cotisation annuelle",
        "paiement récurrent",
        "renouvellement",
        "forfait premium",
        "forfait mensuel",
        "forfait annuel",
      ],
    },
    merchants: [
      "netflix",
      "spotify",
      "disney plus",
      "disney+",
      "hbo max",
      "paramount plus",
      "crunchyroll",
      "mubi",
      "youtube premium",
      "youtube music",
      "apple music",
      "icloud",
      "apple.com/bill",
      "google one",
      "google storage",
      "amazon prime",
      "audible",
      "deezer",
      "tidal",
      "storytel",
      "adobe",
      "creative cloud",
      "microsoft 365",
      "office 365",
      "dropbox",
      "notion",
      "evernote",
      "canva",
      "figma",
      "github",
      "openai",
      "anthropic",
      "midjourney",
      "perplexity",
      "google workspace",
      "protonmail",
      "proton ag",
      "nordvpn",
      "expressvpn",
      "1password",
      "bitwarden",
      "backblaze",
      "duolingo",
      "strava",
      "patreon",
      "substack",
      "linkedin premium",
      "le monde",
      "mediapart",
      "le temps",
      "24 heures",
      "tribune de geneve",
      "nzz",
      "nytimes",
      "new york times",
      "the guardian",
      "the economist",
      "financial times",
    ],
    // "Max" alone is a first name far more often than it is the streaming
    // service, so it only ever hints; "hbo max" above is the real rule.
    ambiguousMerchants: ["max"],
  },
  {
    id: "family",
    strongPhrases: {
      en: [
        "childcare",
        "daycare",
        "nursery",
        "babysitter",
        "babysitting",
        "nanny",
        "school fee",
        "school lunch",
        "school supplies",
        "school trip",
        "child activity",
        "kids activity",
        "summer camp",
        "child care",
        "tuition",
        "music lesson",
        "swimming lessons",
        "toys",
        "nappies",
        "diapers",
        "baby formula",
      ],
      fr: [
        "garde d'enfant",
        "garde enfants",
        "crèche",
        "garderie",
        "nounou",
        "maman de jour",
        "baby-sitter",
        "babysitting",
        "frais scolaires",
        "écolage",
        "cantine scolaire",
        "fournitures scolaires",
        "sortie scolaire",
        "activité enfant",
        "activité enfants",
        "colonie de vacances",
        "parascolaire",
        "cours de musique",
        "cours de natation",
        "jouets",
        "couches",
        "lait infantile",
        "poussette",
      ],
    },
    merchants: [
      "franz carl weber",
      "king jouet",
      "la grande recre",
      "vertbaudet",
      "petit bateau",
      "orchestra premaman",
      "kindercity",
    ],
    merchantFragments: [
      "crèche",
      "creche",
      "nursery",
      "garderie",
      "childcare",
      "kita",
      "kinderkrippe",
      "uape",
      "école",
      "school",
    ],
  },
  {
    id: "pets",
    strongPhrases: {
      en: [
        "pet",
        "pet food",
        "dog food",
        "cat food",
        "cat litter",
        "veterinarian",
        "veterinary",
        "vet",
        "pet grooming",
        "animal hospital",
        "pet insurance",
        "pet store",
        "dog boarding",
        "dog walker",
        "microchip",
      ],
      fr: [
        "animal",
        "animaux",
        "nourriture animaux",
        "nourriture chien",
        "nourriture chat",
        "croquettes",
        "litière",
        "vétérinaire",
        "clinique vétérinaire",
        "toilettage",
        "assurance animaux",
        "animalerie",
        "pension pour chien",
        "promeneur de chien",
        "puce électronique",
      ],
    },
    weakKeywords: {
      en: ["dog", "cat", "puppy", "kitten", "pets"],
      fr: ["chien", "chat", "chiot", "chaton", "animalier"],
    },
    merchants: [
      "zooplus",
      "bitiba",
      "fressnapf",
      "maxi zoo",
      "qualipet",
      "animalis",
      "tom and co",
      "royal canin",
    ],
    merchantFragments: [
      "vet",
      "veterinary",
      "vétérinaire",
      "veterinaire",
      "pet",
      "animalerie",
    ],
  },
  {
    id: "gifts",
    strongPhrases: {
      en: [
        "gift",
        "present",
        "birthday present",
        "wedding gift",
        "gift card",
        "gift voucher",
        "donation",
        "charity",
        "charitable donation",
        "fundraiser",
        "flowers delivery",
        "leaving gift",
        "flowers",
        "bouquet",
        "florist",
      ],
      fr: [
        "cadeau",
        "cadeau anniversaire",
        "cadeau mariage",
        "carte cadeau",
        "bon cadeau",
        "don",
        "donation",
        "association caritative",
        "œuvre caritative",
        "collecte de fonds",
        "livraison de fleurs",
        "pot de départ",
        "fleurs",
        "bouquet",
        "bouquet de fleurs",
        "fleuriste",
        "cadeaux",
      ],
    },
    merchants: [
      "interflora",
      "fleurop",
      "aquarelle",
      "bergamotte",
      "monceau fleurs",
      "unicef",
      "red cross",
      "croix rouge",
      "médecins sans frontières",
      "medecins sans frontieres",
      "msf",
      "wwf",
      "greenpeace",
      "amnesty international",
      "caritas",
      "terre des hommes",
      "handicap international",
      "restos du coeur",
      "gofundme",
      "helloasso",
      "leetchi",
    ],
    merchantFragments: [
      "charity",
      "donation",
      "fondation",
      "foundation",
      "association",
      "fleuriste",
      "florist",
    ],
  },
  {
    id: "fees",
    strongPhrases: {
      en: [
        "bank fee",
        "banking fee",
        "account fee",
        "card fee",
        "credit card fee",
        "debit card fee",
        "atm fee",
        "withdrawal fee",
        "exchange fee",
        "foreign exchange fee",
        "conversion fee",
        "service fee",
        "transaction fee",
        "late fee",
        "administration fee",
        "processing fee",
        "interest charged",
        "overdraft fee",
        "penalty",
        "fine",
      ],
      fr: [
        "frais bancaires",
        "frais de compte",
        "frais de carte",
        "frais carte bancaire",
        "frais de retrait",
        "frais de change",
        "frais de conversion",
        "frais de service",
        "frais de transaction",
        "frais de retard",
        "frais administratifs",
        "frais de dossier",
        "frais de traitement",
        "intérêts débiteurs",
        "frais de découvert",
        "agios",
        "droit de timbre",
        "amende",
        "contravention",
      ],
    },
    merchantFragments: ["fee", "fees", "commission", "frais", "surcharge"],
  },
  /**
   * `other` carries no evidence at all, by design. It is where the classifier
   * lands when nothing else does, never something it can be argued into.
   */
  { id: "other", strongPhrases: {} },
];

export const SEED_BY_CATEGORY: ReadonlyMap<ExpenseCategory, CategorySeed> =
  new Map(CATEGORY_SEEDS.map((seed) => [seed.id, seed]));

/** Every phrase of a bucket, across languages. */
export function allPhrases(
  phrases: PhrasesByLanguage | undefined,
): readonly string[] {
  if (!phrases) return [];
  return Object.values(phrases).flat();
}
