import { createHash } from "node:crypto";
import { mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  ObjectNotFoundError,
  StorageError,
  type StorageDriver,
  type StoredObject,
} from "./types";

/**
 * Local filesystem driver — the default for self-hosted installs.
 *
 * Objects land in a named Docker volume, outside the web root: there is no
 * route that serves this directory statically, so every download goes through
 * an authorized handler.
 *
 * Keys are generated by `attachments` (random hex), but `resolvePath` still
 * refuses anything that escapes the root. Defence in depth: a future caller
 * passing a key from elsewhere should fail loudly rather than read /etc/passwd.
 */
export class LocalStorageDriver implements StorageDriver {
  readonly name = "local" as const;
  private readonly root: string;

  constructor(root: string) {
    this.root = path.resolve(root);
  }

  private resolvePath(key: string): string {
    if (!/^[A-Za-z0-9/_-]+$/.test(key) || key.includes("..")) {
      throw new StorageError(`Refusing unsafe storage key: ${key}`);
    }
    const resolved = path.resolve(this.root, key);
    const rootWithSeparator = this.root.endsWith(path.sep)
      ? this.root
      : `${this.root}${path.sep}`;
    if (!resolved.startsWith(rootWithSeparator)) {
      throw new StorageError(`Storage key escapes the storage root: ${key}`);
    }
    return resolved;
  }

  async put(key: string, body: Buffer): Promise<StoredObject> {
    const target = this.resolvePath(key);
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, body, { mode: 0o640 });
    return {
      key,
      byteSize: body.byteLength,
      checksum: createHash("sha256").update(body).digest("hex"),
    };
  }

  async get(key: string): Promise<Buffer> {
    const target = this.resolvePath(key);
    try {
      return await readFile(target);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "ENOENT") {
        throw new ObjectNotFoundError(key);
      }
      throw new StorageError(`Failed to read stored object ${key}`, {
        cause: error,
      });
    }
  }

  async delete(key: string): Promise<void> {
    await rm(this.resolvePath(key), { force: true });
  }

  async exists(key: string): Promise<boolean> {
    try {
      await stat(this.resolvePath(key));
      return true;
    } catch {
      return false;
    }
  }
}
