/**
 * Storage adapter contract.
 *
 * Receipt binaries live behind this interface so the local-disk default and the
 * optional S3 driver are interchangeable. Object keys are always generated by
 * Balancia (random, opaque) — no user-supplied filename ever becomes part of a
 * path, which removes traversal as a concern at the source.
 */

export interface StoredObject {
  readonly key: string;
  readonly byteSize: number;
  readonly checksum: string;
}

export interface StorageDriver {
  readonly name: "local" | "s3";
  put(key: string, body: Buffer, contentType: string): Promise<StoredObject>;
  get(key: string): Promise<Buffer>;
  delete(key: string): Promise<void>;
  exists(key: string): Promise<boolean>;
}

export class StorageError extends Error {
  constructor(message: string, options?: { cause?: unknown }) {
    super(message, options);
    this.name = "StorageError";
  }
}

export class ObjectNotFoundError extends StorageError {
  constructor(key: string) {
    super(`No stored object for key ${key}`);
    this.name = "ObjectNotFoundError";
  }
}
