import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettier from "eslint-config-prettier/flat";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  prettier,
  {
    // Our own code. src/components/ui is generated by the shadcn CLI and is
    // re-synced from upstream, so it is not held to these house rules.
    ignores: ["src/components/ui/**"],
    rules: {
      // Financial code must not silently coerce bigint/number.
      "no-implicit-coercion": "error",
      "prefer-const": "error",
      eqeqeq: ["error", "smart"],
    },
  },
  {
    /*
     * Domain logic stays framework-free: services, engines, repositories and
     * schemas must not import React or Next.js, so they can be tested and
     * reused from the worker without a request context.
     *
     * The adapter files that exist precisely to bridge the framework are
     * exempt: `actions.ts` (Server Actions), `actor.ts` (reads request
     * headers/cookies), and the browser auth client. They are the boundary,
     * not the domain.
     */
    files: ["src/modules/**/*.ts", "src/lib/**/*.ts"],
    ignores: [
      "src/lib/utils.ts",
      "src/lib/actions.ts",
      "src/lib/security/actor.ts",
      "src/modules/**/actions.ts",
      "src/modules/auth/cookies.ts",
      "src/modules/auth/passkey-client.ts",
    ],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["react", "react-dom", "next", "next/*"],
              message:
                "Domain modules must not depend on React or Next.js. Keep framework code in src/app or src/components.",
            },
          ],
        },
      ],
    },
  },
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "dist/**",
    "next-env.d.ts",
    "public/sw.js",
    "coverage/**",
    "playwright-report/**",
    "test-results/**",
  ]),
]);

export default eslintConfig;
