/**
 * The currency where a device is, read off its time zone.
 *
 * A brand-new account has said nothing about money yet, and the sheet that
 * creates its first group used to answer for it with the euro. That answer is
 * permanent — a group's currency cannot change once it exists — so a Zurich
 * flat share went into euros because nobody had said otherwise. The device
 * had, though: it was already telling the same sheet that its days end at
 * Zurich time. The zone is where somebody is; this table is what that place
 * pays in.
 *
 * The zone and not the language, deliberately. `en-US` is what a great many
 * phones far from America are set to, so a region read off the language would
 * put a London flat share into dollars as confidently as this one put Zurich
 * into euros. A clock set to Europe/London is a much better witness.
 *
 * Grouped by currency rather than by zone, so a reviewer can read "every zone
 * that pays in francs" in one place. Only currencies the app supports appear,
 * and the test beside this file holds every key to a zone the runtime knows
 * and every zone the runtime knows to a row. Where a place officially issues
 * one currency and settles in another, the row says which and why. Zones with
 * nobody living in them — Antarctica, `Etc/*`, `UTC` — are left out, as is
 * Europe/Simferopol, where naming a currency would be taking a side; the
 * caller falls back to its own guess for all of them.
 */

import { isSupportedCurrency } from "./iso-4217";

export const ZONES_BY_CURRENCY: Readonly<Record<string, readonly string[]>> = {
  AED: ["Asia/Dubai"],
  AFN: ["Asia/Kabul"],
  ALL: ["Europe/Tirane"],
  AMD: ["Asia/Yerevan"],
  AOA: ["Africa/Luanda"],
  ARS: [
    "America/Buenos_Aires",
    "America/Argentina/Buenos_Aires",
    "America/Catamarca",
    "America/Argentina/Catamarca",
    "America/Cordoba",
    "America/Argentina/Cordoba",
    "America/Jujuy",
    "America/Argentina/Jujuy",
    "America/Mendoza",
    "America/Argentina/Mendoza",
    "America/Argentina/La_Rioja",
    "America/Argentina/Rio_Gallegos",
    "America/Argentina/Salta",
    "America/Argentina/San_Juan",
    "America/Argentina/San_Luis",
    "America/Argentina/Tucuman",
    "America/Argentina/Ushuaia",
  ],
  AUD: [
    "Australia/Adelaide",
    "Australia/Brisbane",
    "Australia/Broken_Hill",
    "Australia/Darwin",
    "Australia/Eucla",
    "Australia/Hobart",
    "Australia/Lindeman",
    "Australia/Lord_Howe",
    "Australia/Melbourne",
    "Australia/Perth",
    "Australia/Sydney",
    "Indian/Christmas",
    "Indian/Cocos",
    "Pacific/Norfolk",
    "Pacific/Nauru",
    // Kiribati and Tuvalu issue coins of their own and settle in Australian
    // dollars.
    "Pacific/Tarawa",
    "Pacific/Kiritimati",
    "Pacific/Enderbury",
    "Pacific/Kanton",
    "Pacific/Funafuti",
  ],
  AWG: ["America/Aruba"],
  AZN: ["Asia/Baku"],
  BAM: ["Europe/Sarajevo"],
  BBD: ["America/Barbados"],
  BDT: ["Asia/Dhaka"],
  BHD: ["Asia/Bahrain"],
  BIF: ["Africa/Bujumbura"],
  BMD: ["Atlantic/Bermuda"],
  BND: ["Asia/Brunei"],
  BOB: ["America/La_Paz"],
  BRL: [
    "America/Araguaina",
    "America/Bahia",
    "America/Belem",
    "America/Boa_Vista",
    "America/Campo_Grande",
    "America/Cuiaba",
    "America/Eirunepe",
    "America/Fortaleza",
    "America/Maceio",
    "America/Manaus",
    "America/Noronha",
    "America/Porto_Velho",
    "America/Recife",
    "America/Rio_Branco",
    "America/Santarem",
    "America/Sao_Paulo",
  ],
  BSD: ["America/Nassau"],
  BTN: ["Asia/Thimphu"],
  BWP: ["Africa/Gaborone"],
  BYN: ["Europe/Minsk"],
  BZD: ["America/Belize"],
  CAD: [
    "America/Atikokan",
    "America/Coral_Harbour",
    "America/Blanc-Sablon",
    "America/Cambridge_Bay",
    "America/Creston",
    "America/Dawson",
    "America/Dawson_Creek",
    "America/Edmonton",
    "America/Fort_Nelson",
    "America/Glace_Bay",
    "America/Goose_Bay",
    "America/Halifax",
    "America/Inuvik",
    "America/Iqaluit",
    "America/Moncton",
    "America/Rankin_Inlet",
    "America/Regina",
    "America/Resolute",
    "America/St_Johns",
    "America/Swift_Current",
    "America/Toronto",
    "America/Vancouver",
    "America/Whitehorse",
    "America/Winnipeg",
  ],
  CDF: ["Africa/Kinshasa", "Africa/Lubumbashi"],
  CHF: [
    "Europe/Zurich",
    "Europe/Vaduz",
    // A German village inside Switzerland's customs area, where the franc is
    // what is in everybody's wallet.
    "Europe/Busingen",
  ],
  CLP: [
    "America/Santiago",
    "America/Punta_Arenas",
    "America/Coyhaique",
    "Pacific/Easter",
  ],
  CNY: ["Asia/Shanghai", "Asia/Urumqi"],
  COP: ["America/Bogota"],
  CRC: ["America/Costa_Rica"],
  CUP: ["America/Havana"],
  CVE: ["Atlantic/Cape_Verde"],
  CZK: ["Europe/Prague"],
  DJF: ["Africa/Djibouti"],
  DKK: [
    "Europe/Copenhagen",
    "Atlantic/Faeroe",
    "Atlantic/Faroe",
    "America/Godthab",
    "America/Nuuk",
    "America/Danmarkshavn",
    "America/Scoresbysund",
    "America/Thule",
  ],
  DOP: ["America/Santo_Domingo"],
  DZD: ["Africa/Algiers"],
  EGP: ["Africa/Cairo"],
  ERN: ["Africa/Asmera", "Africa/Asmara"],
  ETB: ["Africa/Addis_Ababa"],
  EUR: [
    "Europe/Amsterdam",
    "Europe/Andorra",
    "Europe/Athens",
    "Europe/Berlin",
    "Europe/Bratislava",
    "Europe/Brussels",
    "Europe/Dublin",
    "Europe/Helsinki",
    "Europe/Lisbon",
    "Europe/Ljubljana",
    "Europe/Luxembourg",
    "Europe/Madrid",
    "Europe/Malta",
    "Europe/Mariehamn",
    "Europe/Monaco",
    "Europe/Paris",
    "Europe/Podgorica",
    "Europe/Riga",
    "Europe/Rome",
    "Europe/San_Marino",
    // Bulgaria joined the euro on 1 January 2026.
    "Europe/Sofia",
    "Europe/Tallinn",
    "Europe/Vatican",
    "Europe/Vienna",
    "Europe/Vilnius",
    "Europe/Zagreb",
    "Asia/Nicosia",
    "Asia/Famagusta",
    "Africa/Ceuta",
    "Atlantic/Azores",
    "Atlantic/Canary",
    "Atlantic/Madeira",
    "America/Cayenne",
    "America/Guadeloupe",
    "America/Marigot",
    "America/Martinique",
    "America/Miquelon",
    "America/St_Barthelemy",
    "Indian/Kerguelen",
    "Indian/Mayotte",
    "Indian/Reunion",
  ],
  FJD: ["Pacific/Fiji"],
  FKP: ["Atlantic/Stanley"],
  GBP: [
    "Europe/London",
    "Europe/Guernsey",
    "Europe/Isle_of_Man",
    "Europe/Jersey",
    "Atlantic/South_Georgia",
  ],
  GEL: ["Asia/Tbilisi"],
  GHS: ["Africa/Accra"],
  GIP: ["Europe/Gibraltar"],
  GMD: ["Africa/Banjul"],
  GNF: ["Africa/Conakry"],
  GTQ: ["America/Guatemala"],
  GYD: ["America/Guyana"],
  HKD: ["Asia/Hong_Kong"],
  HNL: ["America/Tegucigalpa"],
  HTG: ["America/Port-au-Prince"],
  HUF: ["Europe/Budapest"],
  IDR: ["Asia/Jakarta", "Asia/Jayapura", "Asia/Makassar", "Asia/Pontianak"],
  ILS: ["Asia/Jerusalem", "Asia/Gaza", "Asia/Hebron"],
  INR: ["Asia/Calcutta", "Asia/Kolkata"],
  IQD: ["Asia/Baghdad"],
  IRR: ["Asia/Tehran"],
  ISK: ["Atlantic/Reykjavik"],
  JMD: ["America/Jamaica"],
  JOD: ["Asia/Amman"],
  JPY: ["Asia/Tokyo"],
  KES: ["Africa/Nairobi"],
  KGS: ["Asia/Bishkek"],
  KHR: ["Asia/Phnom_Penh"],
  KMF: ["Indian/Comoro"],
  KPW: ["Asia/Pyongyang"],
  KRW: ["Asia/Seoul"],
  KWD: ["Asia/Kuwait"],
  KYD: ["America/Cayman"],
  KZT: [
    "Asia/Almaty",
    "Asia/Aqtau",
    "Asia/Aqtobe",
    "Asia/Atyrau",
    "Asia/Oral",
    "Asia/Qostanay",
    "Asia/Qyzylorda",
  ],
  LAK: ["Asia/Vientiane"],
  LBP: ["Asia/Beirut"],
  LKR: ["Asia/Colombo"],
  LRD: ["Africa/Monrovia"],
  LSL: ["Africa/Maseru"],
  LYD: ["Africa/Tripoli"],
  MAD: ["Africa/Casablanca", "Africa/El_Aaiun"],
  MDL: ["Europe/Chisinau"],
  MGA: ["Indian/Antananarivo"],
  MKD: ["Europe/Skopje"],
  MMK: ["Asia/Rangoon", "Asia/Yangon"],
  MNT: ["Asia/Ulaanbaatar", "Asia/Hovd"],
  MOP: ["Asia/Macau"],
  MRU: ["Africa/Nouakchott"],
  MUR: ["Indian/Mauritius"],
  MVR: ["Indian/Maldives"],
  MWK: ["Africa/Blantyre"],
  MXN: [
    "America/Bahia_Banderas",
    "America/Cancun",
    "America/Chihuahua",
    "America/Ciudad_Juarez",
    "America/Hermosillo",
    "America/Matamoros",
    "America/Mazatlan",
    "America/Merida",
    "America/Mexico_City",
    "America/Monterrey",
    "America/Ojinaga",
    "America/Tijuana",
  ],
  MYR: ["Asia/Kuala_Lumpur", "Asia/Kuching"],
  MZN: ["Africa/Maputo"],
  NAD: ["Africa/Windhoek"],
  NGN: ["Africa/Lagos"],
  NIO: ["America/Managua"],
  NOK: ["Europe/Oslo", "Arctic/Longyearbyen"],
  NPR: ["Asia/Katmandu", "Asia/Kathmandu"],
  NZD: [
    "Pacific/Auckland",
    "Pacific/Chatham",
    "Pacific/Fakaofo",
    "Pacific/Niue",
    "Pacific/Pitcairn",
    "Pacific/Rarotonga",
  ],
  OMR: ["Asia/Muscat"],
  PEN: ["America/Lima"],
  PGK: ["Pacific/Port_Moresby", "Pacific/Bougainville"],
  PHP: ["Asia/Manila"],
  PKR: ["Asia/Karachi"],
  PLN: ["Europe/Warsaw"],
  PYG: ["America/Asuncion"],
  QAR: ["Asia/Qatar"],
  RON: ["Europe/Bucharest"],
  RSD: ["Europe/Belgrade"],
  RUB: [
    "Europe/Moscow",
    "Europe/Astrakhan",
    "Europe/Kaliningrad",
    "Europe/Kirov",
    "Europe/Samara",
    "Europe/Saratov",
    "Europe/Ulyanovsk",
    "Europe/Volgograd",
    "Asia/Anadyr",
    "Asia/Barnaul",
    "Asia/Chita",
    "Asia/Irkutsk",
    "Asia/Kamchatka",
    "Asia/Khandyga",
    "Asia/Krasnoyarsk",
    "Asia/Magadan",
    "Asia/Novokuznetsk",
    "Asia/Novosibirsk",
    "Asia/Omsk",
    "Asia/Sakhalin",
    "Asia/Srednekolymsk",
    "Asia/Tomsk",
    "Asia/Ust-Nera",
    "Asia/Vladivostok",
    "Asia/Yakutsk",
    "Asia/Yekaterinburg",
  ],
  RWF: ["Africa/Kigali"],
  SAR: ["Asia/Riyadh"],
  SBD: ["Pacific/Guadalcanal"],
  SCR: ["Indian/Mahe"],
  SDG: ["Africa/Khartoum"],
  SEK: ["Europe/Stockholm"],
  SGD: ["Asia/Singapore"],
  SHP: ["Atlantic/St_Helena"],
  SLE: ["Africa/Freetown"],
  SOS: ["Africa/Mogadishu"],
  SRD: ["America/Paramaribo"],
  SSP: ["Africa/Juba"],
  STN: ["Africa/Sao_Tome"],
  SYP: ["Asia/Damascus"],
  SZL: ["Africa/Mbabane"],
  THB: ["Asia/Bangkok"],
  TJS: ["Asia/Dushanbe"],
  TMT: ["Asia/Ashgabat"],
  TND: ["Africa/Tunis"],
  TOP: ["Pacific/Tongatapu"],
  TRY: ["Europe/Istanbul"],
  TTD: ["America/Port_of_Spain"],
  TWD: ["Asia/Taipei"],
  TZS: ["Africa/Dar_es_Salaam"],
  UAH: ["Europe/Kiev", "Europe/Kyiv"],
  UGX: ["Africa/Kampala"],
  USD: [
    "America/New_York",
    "America/Chicago",
    "America/Denver",
    "America/Los_Angeles",
    "America/Phoenix",
    "America/Anchorage",
    "America/Adak",
    "America/Boise",
    "America/Detroit",
    "America/Indianapolis",
    "America/Indiana/Indianapolis",
    "America/Indiana/Knox",
    "America/Indiana/Marengo",
    "America/Indiana/Petersburg",
    "America/Indiana/Tell_City",
    "America/Indiana/Vevay",
    "America/Indiana/Vincennes",
    "America/Indiana/Winamac",
    "America/Juneau",
    "America/Kentucky/Monticello",
    "America/Louisville",
    "America/Kentucky/Louisville",
    "America/Menominee",
    "America/Metlakatla",
    "America/Nome",
    "America/North_Dakota/Beulah",
    "America/North_Dakota/Center",
    "America/North_Dakota/New_Salem",
    "America/Sitka",
    "America/Yakutat",
    "Pacific/Honolulu",
    // Territories, and the countries that use the dollar as their own.
    "America/Puerto_Rico",
    "America/St_Thomas",
    "America/Tortola",
    "America/Grand_Turk",
    "America/Kralendijk",
    "America/El_Salvador",
    "America/Guayaquil",
    "Pacific/Galapagos",
    // The balboa is coins only; every note in Panama is a dollar.
    "America/Panama",
    "Asia/Dili",
    "Indian/Chagos",
    "Pacific/Guam",
    "Pacific/Saipan",
    "Pacific/Pago_Pago",
    "Pacific/Midway",
    "Pacific/Wake",
    "Pacific/Palau",
    "Pacific/Majuro",
    "Pacific/Kwajalein",
    "Pacific/Kosrae",
    "Pacific/Ponape",
    "Pacific/Pohnpei",
    "Pacific/Truk",
    "Pacific/Chuuk",
  ],
  UYU: ["America/Montevideo"],
  UZS: ["Asia/Tashkent", "Asia/Samarkand"],
  VED: ["America/Caracas"],
  VND: ["Asia/Saigon", "Asia/Ho_Chi_Minh"],
  VUV: ["Pacific/Efate"],
  WST: ["Pacific/Apia"],
  XAF: [
    "Africa/Bangui",
    "Africa/Brazzaville",
    "Africa/Douala",
    "Africa/Libreville",
    "Africa/Malabo",
    "Africa/Ndjamena",
  ],
  XCD: [
    "America/Anguilla",
    "America/Antigua",
    "America/Dominica",
    "America/Grenada",
    "America/Montserrat",
    "America/St_Kitts",
    "America/St_Lucia",
    "America/St_Vincent",
  ],
  // The Caribbean guilder replaced the Antillean one in 2025.
  XCG: ["America/Curacao", "America/Lower_Princes"],
  XOF: [
    "Africa/Abidjan",
    "Africa/Bamako",
    "Africa/Bissau",
    "Africa/Dakar",
    "Africa/Lome",
    "Africa/Niamey",
    "Africa/Ouagadougou",
    "Africa/Porto-Novo",
  ],
  XPF: [
    "Pacific/Tahiti",
    "Pacific/Marquesas",
    "Pacific/Gambier",
    "Pacific/Noumea",
    "Pacific/Wallis",
  ],
  YER: ["Asia/Aden"],
  ZAR: ["Africa/Johannesburg"],
  ZMW: ["Africa/Lusaka"],
  ZWG: ["Africa/Harare"],
};

/** The table turned round, built once. Both are exported for their test. */
export const CURRENCY_BY_ZONE: ReadonlyMap<string, string> = new Map(
  Object.entries(ZONES_BY_CURRENCY).flatMap(([currency, zones]) =>
    zones.map((zone) => [zone, currency] as const),
  ),
);

/**
 * The zone as this runtime names it, which is not always how the device does.
 *
 * Engines disagree over the zones that were renamed — V8 reports
 * `Asia/Calcutta` where Firefox says `Asia/Kolkata` — and both spellings are
 * in the table for those. This catches the rest: a link such as
 * `America/Montreal`, which every engine resolves to a zone that is listed.
 */
function canonical(zone: string): string | null {
  try {
    return new Intl.DateTimeFormat("en-US", {
      timeZone: zone,
    }).resolvedOptions().timeZone;
  } catch {
    return null;
  }
}

/**
 * The currency paid where `zone` is, or null where the table has no answer —
 * no zone, a zone nobody lives in, or one this runtime does not know.
 *
 * Only ever a currency the app supports, so a guess can always be submitted.
 */
export function currencyOfTimezone(
  zone: string | null | undefined,
): string | null {
  if (!zone) return null;
  const currency =
    CURRENCY_BY_ZONE.get(zone) ??
    CURRENCY_BY_ZONE.get(canonical(zone) ?? "") ??
    null;
  return currency !== null && isSupportedCurrency(currency) ? currency : null;
}
