import { NextResponse } from "next/server";
import { themeColorFor } from "@/modules/profile/surface";

/**
 * Web app manifest.
 *
 * Served from a route handler rather than a static file so the icons and
 * start URL stay consistent with the app's routing, and so the response
 * carries the correct `application/manifest+json` content type.
 */
export function GET() {
  const manifest = {
    id: "/",
    name: "Balancia — shared expenses",
    short_name: "Balancia",
    description:
      "Privacy-focused, self-hosted shared expense tracking. Shared expenses. Fairly balanced.",
    start_url: "/dashboard",
    scope: "/",
    display: "standalone",
    orientation: "portrait-primary",
    // The same two values the root layout tints the browser chrome with,
    // rather than a second copy that can disagree with it.
    background_color: themeColorFor("cream"),
    theme_color: themeColorFor("plum"),
    categories: ["finance", "productivity", "utilities"],
    icons: [
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
    /*
     * The home-screen long-press menu.
     *
     * Each carries its own icon. Without one the platform draws a generic
     * glyph — the same generic glyph for both, which makes a menu whose whole
     * job is to tell two destinations apart do nothing of the kind. They are
     * generated by `scripts/generate-icons.ts` and committed, so a build needs
     * no image tooling; the paths are load-bearing at both ends.
     *
     * `short_name` as well as `name`: Android uses the long one in the menu
     * and the short one when a shortcut is dragged out and becomes an icon on
     * the home screen in its own right.
     */
    shortcuts: [
      {
        name: "Your groups",
        short_name: "Groups",
        url: "/dashboard",
        icons: [
          {
            src: "/icons/shortcut-groups-96.png",
            sizes: "96x96",
            type: "image/png",
          },
        ],
      },
      {
        name: "Create a group",
        short_name: "New group",
        url: "/groups/new",
        icons: [
          {
            src: "/icons/shortcut-create-96.png",
            sizes: "96x96",
            type: "image/png",
          },
        ],
      },
    ],
  };

  return NextResponse.json(manifest, {
    headers: {
      "Content-Type": "application/manifest+json",
      "Cache-Control": "public, max-age=3600",
    },
  });
}
