import { NextResponse } from "next/server";
import { themeColorFor } from "@/modules/profile/surface";

/**
 * Web app manifest.
 *
 * Served from a route handler rather than a static file so the icons and
 * start URL stay consistent with the app's routing, and so the response
 * carries the correct `application/manifest+json` content type.
 */
export function GET() {
  const manifest = {
    id: "/",
    name: "Balancia — shared expenses",
    short_name: "Balancia",
    description:
      "Privacy-focused, self-hosted shared expense tracking. Shared expenses. Fairly balanced.",
    start_url: "/dashboard",
    scope: "/",
    display: "standalone",
    orientation: "portrait-primary",
    // The same two values the root layout tints the browser chrome with,
    // rather than a second copy that can disagree with it.
    background_color: themeColorFor("cream"),
    theme_color: themeColorFor("plum"),
    categories: ["finance", "productivity", "utilities"],
    icons: [
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
    /*
     * The home-screen long-press menu.
     *
     * Each carries its own icon. Without one the platform draws a generic
     * glyph — the same generic glyph for both, which makes a menu whose whole
     * job is to tell two destinations apart do nothing of the kind. They are
     * generated by `scripts/generate-icons.ts` and committed, so a build needs
     * no image tooling; the paths are load-bearing at both ends.
     *
     * `short_name` as well as `name`: Android uses the long one in the menu
     * and the short one when a shortcut is dragged out and becomes an icon on
     * the home screen in its own right.
     */
    shortcuts: [
      {
        name: "Your groups",
        short_name: "Groups",
        url: "/dashboard",
        icons: [
          {
            src: "/icons/shortcut-groups-96.png",
            sizes: "96x96",
            type: "image/png",
          },
        ],
      },
      {
        name: "Create a group",
        short_name: "New group",
        url: "/groups/new",
        icons: [
          {
            src: "/icons/shortcut-create-96.png",
            sizes: "96x96",
            type: "image/png",
          },
        ],
      },
    ],
    /*
     * "Balancia" in another app's share sheet.
     *
     * A receipt is photographed before it is entered, a booking arrives as a
     * PDF, and the amount is usually already written down in a message
     * somebody sent. Registering here is what turns each of those into the
     * start of an entry instead of something to retype.
     *
     * `method: POST` with `multipart/form-data` is required for files — a GET
     * share target can carry text and nothing else — and it is why
     * `src/app/sw.ts` intercepts this path rather than a route handler
     * answering it: the worker is the only thing that can take a `File` out of
     * a POST and hand it to a page. `/share` itself is an ordinary GET screen,
     * which is what the worker redirects to.
     *
     * `accept` is deliberately narrow. `image/*` and PDFs are what a receipt
     * is; accepting everything would put Balancia in the share sheet of every
     * text file and video on the device, which is how an app gets turned off
     * there and never turned back on.
     *
     * Not on iOS. Safari implements no share target at all, for installed web
     * apps or otherwise, so this reaches Android and desktop Chromium. The
     * native app's share extension is the other half and is not in this repo.
     */
    share_target: {
      action: "/share",
      method: "POST",
      enctype: "multipart/form-data",
      params: {
        title: "title",
        text: "text",
        url: "url",
        files: [
          {
            name: "media",
            accept: ["image/*", "application/pdf"],
          },
        ],
      },
    },
  };

  return NextResponse.json(manifest, {
    headers: {
      "Content-Type": "application/manifest+json",
      "Cache-Control": "public, max-age=3600",
    },
  });
}
