#!/bin/sh
# Balancia — first-run setup.
#
#   ./scripts/bootstrap.sh
#
# Writes a .env next to compose.yaml holding this instance's database password
# and auth secret. Nothing in this repository contains a usable production
# secret, so every install generates its own.
#
# Safe to re-run: values already present in .env are never touched. That makes
# it usable as a one-liner in front of Compose —
#
#   ./scripts/bootstrap.sh && docker compose up -d --build
#
# Needs only a POSIX shell and /dev/urandom. No openssl, no Node.
set -eu

root_dir=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
env_file="$root_dir/.env"

# Alphanumeric on purpose, not base64. The database password is spliced into a
# connection URL, where a literal '/', '#' or '?' would end the authority
# section — the port stops parsing as a number and PostgreSQL rejects the whole
# string with "Invalid URL". 40 alphanumerics is ~238 bits; the length is doing
# the work, not the alphabet.
random_alnum() {
  LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "$1"
}

# Matches a key only when it has a non-empty value, so a commented-out or
# blank line left over from .env.example still gets filled in.
has_value() {
  grep -qE "^[[:space:]]*$1=.+" "$env_file"
}

# Secrets, not world-readable.
umask 077

if [ ! -e "$env_file" ]; then
  cat > "$env_file" <<'HEADER'
# Balancia configuration — generated by scripts/bootstrap.sh.
#
# The secrets below are unique to this instance. Back this file up: losing
# AUTH_SECRET signs everyone out, and losing POSTGRES_PASSWORD locks you out of
# your own database.
#
# Everything else is optional and documented in .env.example. To run on a
# domain rather than localhost, add APP_URL=https://balancia.example.com.
HEADER
  created=1
else
  created=0
fi

added=0

if ! has_value AUTH_SECRET; then
  printf '\nAUTH_SECRET=%s\n' "$(random_alnum 64)" >> "$env_file"
  echo "Generated AUTH_SECRET."
  added=1
fi

if ! has_value POSTGRES_PASSWORD; then
  printf '\nPOSTGRES_PASSWORD=%s\n' "$(random_alnum 40)" >> "$env_file"
  echo "Generated POSTGRES_PASSWORD."
  added=1
fi

chmod 600 "$env_file"

if [ "$added" -eq 0 ]; then
  echo ".env already has both secrets — left untouched."
elif [ "$created" -eq 1 ]; then
  echo "Wrote .env. Back it up; it is the only copy of these secrets."
else
  echo "Updated .env. Back it up; it is the only copy of these secrets."
fi
